#!/bin/sh

# git hook that runs before a commit
# this script will regenerate the swagger docs(openapi v3 soon) file

pwd

changed=$(git status -s | grep api)

echo "$changed"

# if changed is empty then exit, else regenerate the docs
if [ -z "$changed" ]
then
      exit 0
else
  # regenerate docs
  swag init --generatedTime --parseDependency --parseInternal -d api/ api/*
  go run v3gen/main.go
  git add docs/ # add all files under the generated doc folder to git
fi

exit 0
