#!/bin/sh

# git hook that runs before a push
# this script will regenerate teh openapi.yaml file, and add it to a new commit

echo $(PWD)

swag init --generatedTime --parseDependency --parseInternal -d server/ server/*
git commit -a -m "regenerated openapi filevbs"
git push --no-verify
sleep 1
exit 0