// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFilter = `-- name: CreateFilter :exec

INSERT INTO convoy.filters (
    id, subscription_id, event_type,
    headers, body, raw_headers, raw_body,
    created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateFilterParams struct {
	ID             pgtype.Text
	SubscriptionID pgtype.Text
	EventType      pgtype.Text
	Headers        []byte
	Body           []byte
	RawHeaders     []byte
	RawBody        []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// Filters Queries
// This file contains SQLc queries for the filters service
func (q *Queries) CreateFilter(ctx context.Context, arg CreateFilterParams) error {
	_, err := q.db.Exec(ctx, createFilter,
		arg.ID,
		arg.SubscriptionID,
		arg.EventType,
		arg.Headers,
		arg.Body,
		arg.RawHeaders,
		arg.RawBody,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteFilter = `-- name: DeleteFilter :execrows
DELETE FROM convoy.filters
WHERE id = $1
`

func (q *Queries) DeleteFilter(ctx context.Context, id pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFilter, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findFilterByID = `-- name: FindFilterByID :one
SELECT
    id, subscription_id, event_type,
    headers, body, raw_headers, raw_body,
    created_at, updated_at
FROM convoy.filters
WHERE id = $1
`

type FindFilterByIDRow struct {
	ID             string
	SubscriptionID string
	EventType      string
	Headers        []byte
	Body           []byte
	RawHeaders     []byte
	RawBody        []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) FindFilterByID(ctx context.Context, id pgtype.Text) (FindFilterByIDRow, error) {
	row := q.db.QueryRow(ctx, findFilterByID, id)
	var i FindFilterByIDRow
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.EventType,
		&i.Headers,
		&i.Body,
		&i.RawHeaders,
		&i.RawBody,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findFilterBySubscriptionAndEventType = `-- name: FindFilterBySubscriptionAndEventType :one
SELECT
    id, subscription_id, event_type,
    headers, body, raw_headers, raw_body,
    created_at, updated_at
FROM convoy.filters
WHERE subscription_id = $1 AND event_type = $2
`

type FindFilterBySubscriptionAndEventTypeParams struct {
	SubscriptionID pgtype.Text
	EventType      pgtype.Text
}

type FindFilterBySubscriptionAndEventTypeRow struct {
	ID             string
	SubscriptionID string
	EventType      string
	Headers        []byte
	Body           []byte
	RawHeaders     []byte
	RawBody        []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) FindFilterBySubscriptionAndEventType(ctx context.Context, arg FindFilterBySubscriptionAndEventTypeParams) (FindFilterBySubscriptionAndEventTypeRow, error) {
	row := q.db.QueryRow(ctx, findFilterBySubscriptionAndEventType, arg.SubscriptionID, arg.EventType)
	var i FindFilterBySubscriptionAndEventTypeRow
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.EventType,
		&i.Headers,
		&i.Body,
		&i.RawHeaders,
		&i.RawBody,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findFiltersBySubscriptionID = `-- name: FindFiltersBySubscriptionID :many
SELECT
    id, subscription_id, event_type,
    headers, body, raw_headers, raw_body,
    created_at, updated_at
FROM convoy.filters
WHERE subscription_id = $1
ORDER BY created_at DESC
`

type FindFiltersBySubscriptionIDRow struct {
	ID             string
	SubscriptionID string
	EventType      string
	Headers        []byte
	Body           []byte
	RawHeaders     []byte
	RawBody        []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) FindFiltersBySubscriptionID(ctx context.Context, subscriptionID pgtype.Text) ([]FindFiltersBySubscriptionIDRow, error) {
	rows, err := q.db.Query(ctx, findFiltersBySubscriptionID, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindFiltersBySubscriptionIDRow
	for rows.Next() {
		var i FindFiltersBySubscriptionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.EventType,
			&i.Headers,
			&i.Body,
			&i.RawHeaders,
			&i.RawBody,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFilter = `-- name: UpdateFilter :execrows
UPDATE convoy.filters
SET
    headers = $1,
    body = $2,
    raw_headers = $3,
    raw_body = $4,
    event_type = $5,
    updated_at = $6
WHERE id = $7
`

type UpdateFilterParams struct {
	Headers    []byte
	Body       []byte
	RawHeaders []byte
	RawBody    []byte
	EventType  pgtype.Text
	UpdatedAt  pgtype.Timestamptz
	ID         pgtype.Text
}

func (q *Queries) UpdateFilter(ctx context.Context, arg UpdateFilterParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFilter,
		arg.Headers,
		arg.Body,
		arg.RawHeaders,
		arg.RawBody,
		arg.EventType,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
