// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Filters Queries
	// This file contains SQLc queries for the filters service
	CreateFilter(ctx context.Context, arg CreateFilterParams) error
	DeleteFilter(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	FindFilterByID(ctx context.Context, dollar_1 pgtype.Text) (FindFilterByIDRow, error)
	FindFilterBySubscriptionAndEventType(ctx context.Context, arg FindFilterBySubscriptionAndEventTypeParams) (FindFilterBySubscriptionAndEventTypeRow, error)
	FindFiltersBySubscriptionID(ctx context.Context, dollar_1 pgtype.Text) ([]FindFiltersBySubscriptionIDRow, error)
	UpdateFilter(ctx context.Context, arg UpdateFilterParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
