// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BulkWritePortalAuthTokens(ctx context.Context, arg BulkWritePortalAuthTokensParams) error
	CountPrevPortalLinks(ctx context.Context, arg CountPrevPortalLinksParams) (int64, error)
	CountPrevPortalLinksWithEndpointFilter(ctx context.Context, arg CountPrevPortalLinksWithEndpointFilterParams) (int64, error)
	// Portal Links Queries
	CreatePortalLink(ctx context.Context, arg CreatePortalLinkParams) error
	CreatePortalLinkAuthToken(ctx context.Context, arg CreatePortalLinkAuthTokenParams) error
	CreatePortalLinkEndpoint(ctx context.Context, arg CreatePortalLinkEndpointParams) error
	DeletePortalLink(ctx context.Context, arg DeletePortalLinkParams) error
	DeletePortalLinkEndpoints(ctx context.Context, arg DeletePortalLinkEndpointsParams) error
	FetchPortalLinkById(ctx context.Context, arg FetchPortalLinkByIdParams) (FetchPortalLinkByIdRow, error)
	FetchPortalLinkByMaskId(ctx context.Context, tokenMaskID pgtype.Text) (FetchPortalLinkByMaskIdRow, error)
	FetchPortalLinkByOwnerID(ctx context.Context, arg FetchPortalLinkByOwnerIDParams) (FetchPortalLinkByOwnerIDRow, error)
	FetchPortalLinkByToken(ctx context.Context, token string) (FetchPortalLinkByTokenRow, error)
	FetchPortalLinksByOwnerID(ctx context.Context, ownerID pgtype.Text) ([]FetchPortalLinksByOwnerIDRow, error)
	FetchPortalLinksPaginatedBackward(ctx context.Context, arg FetchPortalLinksPaginatedBackwardParams) ([]FetchPortalLinksPaginatedBackwardRow, error)
	FetchPortalLinksPaginatedBackwardWithEndpointFilter(ctx context.Context, arg FetchPortalLinksPaginatedBackwardWithEndpointFilterParams) ([]FetchPortalLinksPaginatedBackwardWithEndpointFilterRow, error)
	// Paginated queries
	// Note: These queries are complex and may need dynamic construction in the application layer
	// The following are base queries that can be used with dynamic filtering
	FetchPortalLinksPaginatedForward(ctx context.Context, arg FetchPortalLinksPaginatedForwardParams) ([]FetchPortalLinksPaginatedForwardRow, error)
	FetchPortalLinksPaginatedForwardWithEndpointFilter(ctx context.Context, arg FetchPortalLinksPaginatedForwardWithEndpointFilterParams) ([]FetchPortalLinksPaginatedForwardWithEndpointFilterRow, error)
	UpdateEndpointOwnerID(ctx context.Context, arg UpdateEndpointOwnerIDParams) error
	UpdatePortalLink(ctx context.Context, arg UpdatePortalLinkParams) error
}

var _ Querier = (*Queries)(nil)
