export const CONVOY_AUTH_KEY = 'CONVOY_AUTH';
export const CONVOY_AUTH_TOKENS_KEY = 'CONVOY_AUTH_TOKENS';
export const CONVOY_LAST_AUTH_LOCATION = 'CONVOY_LAST_AUTH_LOCATION';
export const CONVOY_DASHBOARD_DOMAIN = 'dashboard.convoy.io';
