project_name: convoy

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

# https://goreleaser.com/customization/archive/
archives:
  - name_template: "{{ .ProjectName}}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

# https://goreleaser.com/customization/nfpm/
nfpms:
  - id: debrpm
    license: MPL-2.0
    maintainer: frain-dev
    homepage: https://getconvoy.io/
    description: "A Cloud native webhook service"
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - rpm
      - deb

  - id: apk
    license: MPL-2.0
    maintainer: frain-dev
    homepage: https://getconvoy.io/
    description: "A Cloud native webhook service"
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - apk

checksum:
  name_template: "{{ .ProjectName}}_checksums.txt"
