project_name: convoy

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd
    id: cobin
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: lib
    skip: true

# https://goreleaser.com/customization/archive/
archives:
  - name_template: "{{ .ProjectName}}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    id: cobin-archive
    builds:
      - cobin

# https://goreleaser.com/customization/publishers/
publishers:
  - name: cloudsmith-raw
    ids:
      - cobin-archive
    dir: "{{ dir .ArtifactPath }}"
    cmd: cloudsmith push raw --version={{ .Version }} convoy/convoy {{ .ArtifactName }}
    env: 
     - CLOUDSMITH_API_KEY={{ .Env.CLOUDSMITH_API_KEY }}


dockers:
  - image_templates: 
    - "docker.cloudsmith.io/convoy/convoy/{{ .Env.REPO_NAME }}:{{ .Tag }}"
    goos: linux
    goarch: amd64
    dockerfile: release.Dockerfile
    extra_files:
      - configs/local/start.sh
    ids:
      - cobin
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=A fast & secure open source webhooks service
      - --label=org.opencontainers.image.url=https://github.com/{{ .Env.REPO_NAME }}
      - --label=org.opencontainers.image.source=https://github.com/{{ .Env.REPO_NAME }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.licenses=MPL-2.0

  - image_templates: 
    - "docker.cloudsmith.io/convoy/convoy/{{ .Env.REPO_NAME }}:{{ .Tag }}-slim"
    goos: linux
    goarch: amd64
    dockerfile: slim.Dockerfile
    ids:
      - cobin
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=A fast & secure open source webhooks service
      - --label=org.opencontainers.image.url=https://github.com/{{ .Env.REPO_NAME }}
      - --label=org.opencontainers.image.source=https://github.com/{{ .Env.REPO_NAME }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.licenses=MPL-2.0

checksum:
  name_template: "{{ .ProjectName}}_checksums.txt"

release:
  ids:
    - lib
