version: "3"

volumes:
  postgres_data:
  redis_data:

services:
    jaeger:
      image: jaegertracing/all-in-one:1.53
      environment:
        COLLECTOR_ZIPKIN_HOST_POST: ":9411"
      ports: 
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
        - "16686:16686"
        - "4317:4317"
        - "4318:4318" 
        - "14250:14250"
        - "14268:14268"
        - "14269:14269"
        - "9411:9411"

    postgres:
      image: postgres:15.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_DB: convoy
        POSTGRES_USER: convoy
        POSTGRES_PASSWORD: convoy
        PGDATA: /data/postgres
      volumes:
        - ./postgres_data:/data/postgres
      ports:
        - "5432:5432"

    redis_server:
        image: redis:7-alpine
        restart: always
        volumes:
          - ./redis_data:/data
        ports:
          - "6379:6379"
