version: "3"

volumes:
  postgres_data:
  redis_data:
  typesense_data:

services:
    postgres:
      image: postgres:15.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_DB: convoy
        POSTGRES_USER: convoy
        POSTGRES_PASSWORD: convoy
        PGDATA: /data/postgres
      volumes:
        - ./postgres_data:/data/postgres
      ports:
        - "5432:5432"

    redis_server:
        image: redis:alpine
        restart: always
        volumes:
          - ./redis_data:/data
        ports:
          - "6379:6379"

    typesense:
        image: typesense/typesense:0.22.2
        restart: always
        environment:
          TYPESENSE_DATA_DIR: /data/typesense
          TYPESENSE_ENABLE_CORS: "true"
          TYPESENSE_API_KEY: "convoy"
        volumes:
          - ./typesense_data:/data/typesense
        ports:
          - "8108:8108"

