# syntax=docker/dockerfile:1
FROM node:25 as node-env
WORKDIR /app
COPY ./web/ui/dashboard .
RUN git config --global url."https://".insteadOf git://
RUN npm install
RUN npm run build

FROM golang:1.25 as build-env
WORKDIR /go/src/frain-dev/convoy

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

ENV GOCACHE=/root/.cache/go-build
ENV GOMODCACHE=/go/pkg/mod

COPY ./go.mod /go/src/frain-dev/convoy
COPY ./go.sum /go/src/frain-dev/convoy

COPY --from=node-env /app/dist /go/src/frain-dev/convoy/api/ui/build

RUN go mod download
RUN go mod verify

COPY . .

RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    go build -ldflags="-w -s" -o /go/bin/cmd ./cmd

FROM alpine:3.22.2
COPY --from=build-env /go/bin/cmd /
COPY --from=build-env /go/src/frain-dev/convoy/internal/email/templates/* templates/
COPY --from=build-env /go/src/frain-dev/convoy/configs/local/start.sh /
COPY --from=build-env /go/src/frain-dev/convoy/api/ui/build /ui/build

RUN chmod +x /cmd
RUN apk add --no-cache gcompat

EXPOSE 8080
