#!/bin/sh

# git hook that runs before a push
# this script will regenerate teh openapi.yaml file, and add it to a new commit

swag init --generatedTime --parseDependency --parseInternal -d server/ server/*

exit 0
