// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ConvoyUser struct {
	ID                         string
	FirstName                  string
	LastName                   string
	Email                      string
	Password                   string
	EmailVerified              bool
	ResetPasswordToken         pgtype.Text
	EmailVerificationToken     pgtype.Text
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	DeletedAt                  pgtype.Timestamptz
	ResetPasswordExpiresAt     pgtype.Timestamptz
	EmailVerificationExpiresAt pgtype.Timestamptz
	AuthType                   string
}
