// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ============================================================================
	// COUNT Operations
	// ============================================================================
	CountUsers(ctx context.Context) (pgtype.Int8, error)
	// Users Queries
	// ============================================================================
	// CREATE Operations
	// ============================================================================
	CreateUser(ctx context.Context, arg CreateUserParams) error
	FindUserByEmail(ctx context.Context, email pgtype.Text) (FindUserByEmailRow, error)
	FindUserByEmailVerificationToken(ctx context.Context, emailVerificationToken pgtype.Text) (FindUserByEmailVerificationTokenRow, error)
	// ============================================================================
	// FETCH Operations
	// ============================================================================
	FindUserByID(ctx context.Context, id pgtype.Text) (FindUserByIDRow, error)
	FindUserByToken(ctx context.Context, resetPasswordToken pgtype.Text) (FindUserByTokenRow, error)
	// ============================================================================
	// UPDATE Operations
	// ============================================================================
	UpdateUser(ctx context.Context, arg UpdateUserParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
