// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountInstanceAdminUsers(ctx context.Context) (int64, error)
	CountOrganisationAdminUsers(ctx context.Context) (int64, error)
	CountPrevOrganisationMembers(ctx context.Context, arg CountPrevOrganisationMembersParams) (int64, error)
	CountPrevUserOrganisations(ctx context.Context, arg CountPrevUserOrganisationsParams) (int64, error)
	// Organisation Members SQLc Queries
	// Migration from database/postgres/organisation_member.go to SQLc
	// ===========================================================================
	// Core CRUD Operations
	// ===========================================================================
	CreateOrganisationMember(ctx context.Context, arg CreateOrganisationMemberParams) error
	DeleteOrganisationMember(ctx context.Context, arg DeleteOrganisationMemberParams) error
	FetchAnyOrganisationAdminByUserID(ctx context.Context, userID string) (FetchAnyOrganisationAdminByUserIDRow, error)
	// ===========================================================================
	// Admin-Specific Queries
	// ===========================================================================
	FetchInstanceAdminByUserID(ctx context.Context, userID string) (FetchInstanceAdminByUserIDRow, error)
	// ===========================================================================
	// Fetch Single Member Queries (with User Metadata)
	// ===========================================================================
	FetchOrganisationMemberByID(ctx context.Context, arg FetchOrganisationMemberByIDParams) (FetchOrganisationMemberByIDRow, error)
	FetchOrganisationMemberByUserID(ctx context.Context, arg FetchOrganisationMemberByUserIDParams) (FetchOrganisationMemberByUserIDRow, error)
	// ===========================================================================
	// Pagination Queries - Organisation Members
	// ===========================================================================
	FetchOrganisationMembersPaginated(ctx context.Context, arg FetchOrganisationMembersPaginatedParams) ([]FetchOrganisationMembersPaginatedRow, error)
	// ===========================================================================
	// Pagination Queries - User Organisations
	// ===========================================================================
	FetchUserOrganisationsPaginated(ctx context.Context, arg FetchUserOrganisationsPaginatedParams) ([]FetchUserOrganisationsPaginatedRow, error)
	// ===========================================================================
	// Project Queries
	// ===========================================================================
	FindUserProjects(ctx context.Context, userID string) ([]FindUserProjectsRow, error)
	HasInstanceAdminAccess(ctx context.Context, userID string) (pgtype.Bool, error)
	IsFirstInstanceAdmin(ctx context.Context, userID string) (bool, error)
	UpdateOrganisationMember(ctx context.Context, arg UpdateOrganisationMemberParams) error
}

var _ Querier = (*Queries)(nil)
