// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// ============================================================================
// convoy.feature_flags
// ============================================================================

const fetchFeatureFlagByKey = `-- name: FetchFeatureFlagByKey :one
SELECT id, feature_key, enabled, created_at, updated_at
FROM convoy.feature_flags
WHERE feature_key = $1
`

type FetchFeatureFlagByKeyRow struct {
	ID         string
	FeatureKey string
	Enabled    bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) FetchFeatureFlagByKey(ctx context.Context, featureKey pgtype.Text) (FetchFeatureFlagByKeyRow, error) {
	row := q.db.QueryRow(ctx, fetchFeatureFlagByKey, featureKey)
	var i FetchFeatureFlagByKeyRow
	err := row.Scan(
		&i.ID,
		&i.FeatureKey,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fetchFeatureFlagByID = `-- name: FetchFeatureFlagByID :one
SELECT id, feature_key, enabled, created_at, updated_at
FROM convoy.feature_flags
WHERE id = $1
`

type FetchFeatureFlagByIDRow struct {
	ID         string
	FeatureKey string
	Enabled    bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) FetchFeatureFlagByID(ctx context.Context, id pgtype.Text) (FetchFeatureFlagByIDRow, error) {
	row := q.db.QueryRow(ctx, fetchFeatureFlagByID, id)
	var i FetchFeatureFlagByIDRow
	err := row.Scan(
		&i.ID,
		&i.FeatureKey,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const loadFeatureFlags = `-- name: LoadFeatureFlags :many
SELECT id, feature_key, enabled, created_at, updated_at
FROM convoy.feature_flags
ORDER BY feature_key
`

type LoadFeatureFlagsRow struct {
	ID         string
	FeatureKey string
	Enabled    bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) LoadFeatureFlags(ctx context.Context) ([]LoadFeatureFlagsRow, error) {
	rows, err := q.db.Query(ctx, loadFeatureFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadFeatureFlagsRow
	for rows.Next() {
		var i LoadFeatureFlagsRow
		if err := rows.Scan(
			&i.ID,
			&i.FeatureKey,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeatureFlag = `-- name: UpdateFeatureFlag :exec
UPDATE convoy.feature_flags
SET enabled = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateFeatureFlagParams struct {
	Enabled bool
	ID      pgtype.Text
}

func (q *Queries) UpdateFeatureFlag(ctx context.Context, arg UpdateFeatureFlagParams) error {
	_, err := q.db.Exec(ctx, updateFeatureFlag, arg.Enabled, arg.ID)
	return err
}

// ============================================================================
// convoy.feature_flag_overrides
// ============================================================================

const fetchFeatureFlagOverride = `-- name: FetchFeatureFlagOverride :one
SELECT id, feature_flag_id, owner_type, owner_id, enabled, enabled_at, enabled_by, created_at, updated_at
FROM convoy.feature_flag_overrides
WHERE owner_type = $1 AND owner_id = $2 AND feature_flag_id = $3
`

type FetchFeatureFlagOverrideParams struct {
	OwnerType     pgtype.Text
	OwnerID       pgtype.Text
	FeatureFlagID pgtype.Text
}

type FetchFeatureFlagOverrideRow struct {
	ID            string
	FeatureFlagID string
	OwnerType     string
	OwnerID       string
	Enabled       bool
	EnabledAt     pgtype.Timestamptz
	EnabledBy     pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) FetchFeatureFlagOverride(ctx context.Context, arg FetchFeatureFlagOverrideParams) (FetchFeatureFlagOverrideRow, error) {
	row := q.db.QueryRow(ctx, fetchFeatureFlagOverride, arg.OwnerType, arg.OwnerID, arg.FeatureFlagID)
	var i FetchFeatureFlagOverrideRow
	err := row.Scan(
		&i.ID,
		&i.FeatureFlagID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Enabled,
		&i.EnabledAt,
		&i.EnabledBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const loadFeatureFlagOverridesByOwner = `-- name: LoadFeatureFlagOverridesByOwner :many
SELECT id, feature_flag_id, owner_type, owner_id, enabled, enabled_at, enabled_by, created_at, updated_at
FROM convoy.feature_flag_overrides
WHERE owner_type = $1 AND owner_id = $2
`

type LoadFeatureFlagOverridesByOwnerParams struct {
	OwnerType pgtype.Text
	OwnerID   pgtype.Text
}

type LoadFeatureFlagOverridesByOwnerRow struct {
	ID            string
	FeatureFlagID string
	OwnerType     string
	OwnerID       string
	Enabled       bool
	EnabledAt     pgtype.Timestamptz
	EnabledBy     pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) LoadFeatureFlagOverridesByOwner(ctx context.Context, arg LoadFeatureFlagOverridesByOwnerParams) ([]LoadFeatureFlagOverridesByOwnerRow, error) {
	rows, err := q.db.Query(ctx, loadFeatureFlagOverridesByOwner, arg.OwnerType, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadFeatureFlagOverridesByOwnerRow
	for rows.Next() {
		var i LoadFeatureFlagOverridesByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.FeatureFlagID,
			&i.OwnerType,
			&i.OwnerID,
			&i.Enabled,
			&i.EnabledAt,
			&i.EnabledBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadFeatureFlagOverridesByFeatureFlag = `-- name: LoadFeatureFlagOverridesByFeatureFlag :many
SELECT id, feature_flag_id, owner_type, owner_id, enabled, enabled_at, enabled_by, created_at, updated_at
FROM convoy.feature_flag_overrides
WHERE feature_flag_id = $1
`

type LoadFeatureFlagOverridesByFeatureFlagRow struct {
	ID            string
	FeatureFlagID string
	OwnerType     string
	OwnerID       string
	Enabled       bool
	EnabledAt     pgtype.Timestamptz
	EnabledBy     pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) LoadFeatureFlagOverridesByFeatureFlag(ctx context.Context, featureFlagID pgtype.Text) ([]LoadFeatureFlagOverridesByFeatureFlagRow, error) {
	rows, err := q.db.Query(ctx, loadFeatureFlagOverridesByFeatureFlag, featureFlagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadFeatureFlagOverridesByFeatureFlagRow
	for rows.Next() {
		var i LoadFeatureFlagOverridesByFeatureFlagRow
		if err := rows.Scan(
			&i.ID,
			&i.FeatureFlagID,
			&i.OwnerType,
			&i.OwnerID,
			&i.Enabled,
			&i.EnabledAt,
			&i.EnabledBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeatureFlagOverride = `-- name: UpsertFeatureFlagOverride :exec
INSERT INTO convoy.feature_flag_overrides (id, feature_flag_id, owner_type, owner_id, enabled, enabled_at, enabled_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (owner_type, owner_id, feature_flag_id)
DO UPDATE SET enabled = $5, enabled_at = $6, enabled_by = $7, updated_at = NOW()
`

type UpsertFeatureFlagOverrideParams struct {
	ID            pgtype.Text
	FeatureFlagID pgtype.Text
	OwnerType     pgtype.Text
	OwnerID       pgtype.Text
	Enabled       bool
	EnabledAt     pgtype.Timestamptz
	EnabledBy     pgtype.Text
}

func (q *Queries) UpsertFeatureFlagOverride(ctx context.Context, arg UpsertFeatureFlagOverrideParams) error {
	_, err := q.db.Exec(ctx, upsertFeatureFlagOverride,
		arg.ID,
		arg.FeatureFlagID,
		arg.OwnerType,
		arg.OwnerID,
		arg.Enabled,
		arg.EnabledAt,
		arg.EnabledBy,
	)
	return err
}

const deleteFeatureFlagOverride = `-- name: DeleteFeatureFlagOverride :exec
DELETE FROM convoy.feature_flag_overrides
WHERE owner_type = $1 AND owner_id = $2 AND feature_flag_id = $3
`

type DeleteFeatureFlagOverrideParams struct {
	OwnerType     pgtype.Text
	OwnerID       pgtype.Text
	FeatureFlagID pgtype.Text
}

func (q *Queries) DeleteFeatureFlagOverride(ctx context.Context, arg DeleteFeatureFlagOverrideParams) error {
	_, err := q.db.Exec(ctx, deleteFeatureFlagOverride, arg.OwnerType, arg.OwnerID, arg.FeatureFlagID)
	return err
}

// ============================================================================
// convoy.early_adopter_features
// ============================================================================

const fetchEarlyAdopterFeature = `-- name: FetchEarlyAdopterFeature :one
SELECT id, organisation_id, feature_key, enabled, enabled_by, enabled_at, created_at, updated_at
FROM convoy.early_adopter_features
WHERE organisation_id = $1 AND feature_key = $2
`

type FetchEarlyAdopterFeatureParams struct {
	OrganisationID pgtype.Text
	FeatureKey     pgtype.Text
}

type FetchEarlyAdopterFeatureRow struct {
	ID             string
	OrganisationID string
	FeatureKey     string
	Enabled        bool
	EnabledBy      pgtype.Text
	EnabledAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) FetchEarlyAdopterFeature(ctx context.Context, arg FetchEarlyAdopterFeatureParams) (FetchEarlyAdopterFeatureRow, error) {
	row := q.db.QueryRow(ctx, fetchEarlyAdopterFeature, arg.OrganisationID, arg.FeatureKey)
	var i FetchEarlyAdopterFeatureRow
	err := row.Scan(
		&i.ID,
		&i.OrganisationID,
		&i.FeatureKey,
		&i.Enabled,
		&i.EnabledBy,
		&i.EnabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const loadEarlyAdopterFeaturesByOrg = `-- name: LoadEarlyAdopterFeaturesByOrg :many
SELECT id, organisation_id, feature_key, enabled, enabled_by, enabled_at, created_at, updated_at
FROM convoy.early_adopter_features
WHERE organisation_id = $1
ORDER BY feature_key
`

type LoadEarlyAdopterFeaturesByOrgRow struct {
	ID             string
	OrganisationID string
	FeatureKey     string
	Enabled        bool
	EnabledBy      pgtype.Text
	EnabledAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) LoadEarlyAdopterFeaturesByOrg(ctx context.Context, organisationID pgtype.Text) ([]LoadEarlyAdopterFeaturesByOrgRow, error) {
	rows, err := q.db.Query(ctx, loadEarlyAdopterFeaturesByOrg, organisationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadEarlyAdopterFeaturesByOrgRow
	for rows.Next() {
		var i LoadEarlyAdopterFeaturesByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganisationID,
			&i.FeatureKey,
			&i.Enabled,
			&i.EnabledBy,
			&i.EnabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEarlyAdopterFeature = `-- name: UpsertEarlyAdopterFeature :exec
INSERT INTO convoy.early_adopter_features (id, organisation_id, feature_key, enabled, enabled_by, enabled_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (organisation_id, feature_key)
DO UPDATE SET enabled = $4, enabled_by = $5, enabled_at = $6, updated_at = NOW()
`

type UpsertEarlyAdopterFeatureParams struct {
	ID             pgtype.Text
	OrganisationID pgtype.Text
	FeatureKey     pgtype.Text
	Enabled        bool
	EnabledBy      pgtype.Text
	EnabledAt      pgtype.Timestamptz
}

func (q *Queries) UpsertEarlyAdopterFeature(ctx context.Context, arg UpsertEarlyAdopterFeatureParams) error {
	_, err := q.db.Exec(ctx, upsertEarlyAdopterFeature,
		arg.ID,
		arg.OrganisationID,
		arg.FeatureKey,
		arg.Enabled,
		arg.EnabledBy,
		arg.EnabledAt,
	)
	return err
}

const deleteEarlyAdopterFeature = `-- name: DeleteEarlyAdopterFeature :exec
DELETE FROM convoy.early_adopter_features
WHERE organisation_id = $1 AND feature_key = $2
`

type DeleteEarlyAdopterFeatureParams struct {
	OrganisationID pgtype.Text
	FeatureKey     pgtype.Text
}

func (q *Queries) DeleteEarlyAdopterFeature(ctx context.Context, arg DeleteEarlyAdopterFeatureParams) error {
	_, err := q.db.Exec(ctx, deleteEarlyAdopterFeature, arg.OrganisationID, arg.FeatureKey)
	return err
}
