// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// NOTE: This is a stub file. Run `sqlc generate` to generate the real implementation.

package repo

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	WithTx(tx pgx.Tx) *Queries
	// Group 1: Simple CRUD Operations
	CreateEvent(ctx context.Context, arg CreateEventParams) error
	CreateEventEndpoints(ctx context.Context, eventID string, endpointID string) error
	UpdateEventEndpoints(ctx context.Context, endpoints string, projectID string, id string) error
	UpdateEventStatus(ctx context.Context, status string, projectID string, id string) error
	FindEventByID(ctx context.Context, id string, projectID string) (FindEventByIDRow, error)

	// Group 2: Batch Reads & Counting
	FindEventsByIDs(ctx context.Context, ids []string, projectID string) ([]FindEventsByIDsRow, error)
	FindEventsByIdempotencyKey(ctx context.Context, idempotencyKey string, projectID string) ([]FindEventsByIdempotencyKeyRow, error)
	FindFirstEventWithIdempotencyKey(ctx context.Context, idempotencyKey string, projectID string) (FindFirstEventWithIdempotencyKeyRow, error)
	CountProjectMessages(ctx context.Context, projectID string) (int64, error)
	CountEvents(ctx context.Context, arg CountEventsParams) (int64, error)

	// Group 3: Complex Pagination
	LoadEventsPagedExists(ctx context.Context, arg LoadEventsPagedExistsParams) ([]LoadEventsPagedExistsRow, error)
	LoadEventsPagedSearch(ctx context.Context, arg LoadEventsPagedSearchParams) ([]LoadEventsPagedSearchRow, error)
	CountPrevEventsExists(ctx context.Context, arg CountPrevEventsExistsParams) (bool, error)
	CountPrevEventsSearch(ctx context.Context, arg CountPrevEventsSearchParams) (bool, error)

	// Group 4: Deletion & Maintenance
	SoftDeleteProjectEvents(ctx context.Context, projectID string, startDate time.Time, endDate time.Time) error
	HardDeleteProjectEvents(ctx context.Context, projectID string, startDate time.Time, endDate time.Time) error
	HardDeleteTokenizedEvents(ctx context.Context, projectID string) error
	CopyRowsFromEventsToEventsSearch(ctx context.Context, projectID string, interval int32) error

	// Group 5: Partition Management
	PartitionEventsTable(ctx context.Context) error
	UnPartitionEventsTable(ctx context.Context) error
	PartitionEventsSearchTable(ctx context.Context) error
	UnPartitionEventsSearchTable(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)

// Parameter structs (will be properly generated by sqlc)
type CreateEventParams struct {
	ID               string
	EventType        string
	Endpoints        string
	ProjectID        string
	SourceID         pgtype.Text
	Headers          []byte
	Raw              string
	Data             []byte
	URLQueryParams   string
	IdempotencyKey   string
	IsDuplicateEvent bool
	AcknowledgedAt   pgtype.Timestamptz
	Metadata         pgtype.Text
	Status           string
}

type CountEventsParams struct {
	ProjectID      string
	StartDate      time.Time
	EndDate        time.Time
	HasEndpointIds bool
	EndpointIds    []string
	HasSourceID    bool
	SourceID       string
}

type LoadEventsPagedExistsParams struct {
	HasEndpointOrOwnerFilter bool
	HasOwnerID               bool
	OwnerID                  string
	HasEndpointIds           bool
	EndpointIds              []string
	ProjectID                string
	HasIdempotencyKey        bool
	IdempotencyKey           string
	StartDate                time.Time
	EndDate                  time.Time
	HasSourceIds             bool
	SourceIds                []string
	HasBrokerMessageID       bool
	BrokerMessageID          string
	HasCursor                bool
	Cursor                   string
	CursorGte                bool
	SortAsc                  bool
	Limit                    int32
}

type LoadEventsPagedSearchParams struct {
	ProjectID          string
	HasIdempotencyKey  bool
	IdempotencyKey     string
	StartDate          time.Time
	EndDate            time.Time
	HasSourceIds       bool
	SourceIds          []string
	HasEndpointIds     bool
	EndpointIds        []string
	HasBrokerMessageID bool
	BrokerMessageID    string
	HasQuery           bool
	Query              string
	HasCursor          bool
	Cursor             string
	CursorGte          bool
	SortAsc            bool
	Limit              int32
}

type CountPrevEventsExistsParams struct {
	ProjectID          string
	HasIdempotencyKey  bool
	IdempotencyKey     string
	StartDate          time.Time
	EndDate            time.Time
	HasSourceIds       bool
	SourceIds          []string
	HasEndpointIds     bool
	EndpointIds        []string
	HasBrokerMessageID bool
	BrokerMessageID    string
	SortAsc            bool
	Cursor             string
}

type CountPrevEventsSearchParams struct {
	ProjectID          string
	HasIdempotencyKey  bool
	IdempotencyKey     string
	StartDate          time.Time
	EndDate            time.Time
	HasSourceIds       bool
	SourceIds          []string
	HasEndpointIds     bool
	EndpointIds        []string
	HasBrokerMessageID bool
	BrokerMessageID    string
	HasQuery           bool
	Query              string
	SortAsc            bool
	Cursor             string
}

// Row structs (will be properly generated by sqlc)
type FindEventByIDRow struct {
	ID                 string
	EventType          string
	Endpoints          string
	ProjectID          string
	Raw                string
	Data               []byte
	Headers            []byte
	IsDuplicateEvent   bool
	SourceID           string
	IdempotencyKey     string
	URLQueryParams     string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	AcknowledgedAt     pgtype.Timestamptz
	Metadata           pgtype.Text
	Status             string
	SourceMetadataID   string
	SourceMetadataName string
}

type FindEventsByIDsRow struct {
	ID                 string
	ProjectID          string
	IsDuplicateEvent   bool
	EventType          string
	SourceID           string
	IdempotencyKey     string
	URLQueryParams     string
	Headers            []byte
	Raw                string
	Data               []byte
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          pgtype.Timestamptz
	AcknowledgedAt     pgtype.Timestamptz
	SourceMetadataID   string
	SourceMetadataName string
}

type FindEventsByIdempotencyKeyRow struct {
	ID string
}

type FindFirstEventWithIdempotencyKeyRow struct {
	ID string
}

type LoadEventsPagedExistsRow struct {
	ID                 string
	ProjectID          string
	EventType          string
	IsDuplicateEvent   bool
	SourceID           string
	Headers            []byte
	Raw                string
	Data               []byte
	CreatedAt          time.Time
	IdempotencyKey     string
	URLQueryParams     string
	UpdatedAt          time.Time
	DeletedAt          pgtype.Timestamptz
	AcknowledgedAt     pgtype.Timestamptz
	Metadata           pgtype.Text
	Status             string
	SourceMetadataID   string
	SourceMetadataName string
}

type LoadEventsPagedSearchRow struct {
	ID                 string
	ProjectID          string
	EventType          string
	IsDuplicateEvent   bool
	SourceID           string
	Headers            []byte
	Raw                string
	Data               []byte
	CreatedAt          time.Time
	IdempotencyKey     string
	URLQueryParams     string
	UpdatedAt          time.Time
	DeletedAt          pgtype.Timestamptz
	AcknowledgedAt     pgtype.Timestamptz
	Metadata           string
	Status             string
	SourceMetadataID   string
	SourceMetadataName string
}
