// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckEncryptionStatus(ctx context.Context) (bool, error)
	CountPrevEndpoints(ctx context.Context, arg CountPrevEndpointsParams) (pgtype.Int8, error)
	CountProjectEndpoints(ctx context.Context, projectID pgtype.Text) (pgtype.Int8, error)
	// Endpoints Queries
	CreateEndpoint(ctx context.Context, arg CreateEndpointParams) error
	DeleteEndpoint(ctx context.Context, arg DeleteEndpointParams) error
	DeleteEndpointSubscriptions(ctx context.Context, arg DeleteEndpointSubscriptionsParams) error
	DeletePortalLinkEndpoints(ctx context.Context, endpointID pgtype.Text) error
	FetchEndpointIDsByOwnerID(ctx context.Context, arg FetchEndpointIDsByOwnerIDParams) ([]string, error)
	// Note: Returns results in ASC order. Caller must reverse to get DESC order.
	FetchEndpointsPagedBackward(ctx context.Context, arg FetchEndpointsPagedBackwardParams) ([]FetchEndpointsPagedBackwardRow, error)
	FetchEndpointsPagedForward(ctx context.Context, arg FetchEndpointsPagedForwardParams) ([]FetchEndpointsPagedForwardRow, error)
	FindEndpointByID(ctx context.Context, arg FindEndpointByIDParams) (FindEndpointByIDRow, error)
	FindEndpointByTargetURL(ctx context.Context, arg FindEndpointByTargetURLParams) (FindEndpointByTargetURLRow, error)
	FindEndpointsByAppID(ctx context.Context, arg FindEndpointsByAppIDParams) ([]FindEndpointsByAppIDRow, error)
	FindEndpointsByIDs(ctx context.Context, arg FindEndpointsByIDsParams) ([]FindEndpointsByIDsRow, error)
	FindEndpointsByOwnerID(ctx context.Context, arg FindEndpointsByOwnerIDParams) ([]FindEndpointsByOwnerIDRow, error)
	UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (pgconn.CommandTag, error)
	UpdateEndpointSecrets(ctx context.Context, arg UpdateEndpointSecretsParams) (UpdateEndpointSecretsRow, error)
	UpdateEndpointStatus(ctx context.Context, arg UpdateEndpointStatusParams) (UpdateEndpointStatusRow, error)
}

var _ Querier = (*Queries)(nil)
