// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"database/sql/driver"
	"fmt"
)

type ConvoyDeliveryMode string

const (
	ConvoyDeliveryModeAtLeastOnce ConvoyDeliveryMode = "at_least_once"
	ConvoyDeliveryModeAtMostOnce  ConvoyDeliveryMode = "at_most_once"
)

func (e *ConvoyDeliveryMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConvoyDeliveryMode(s)
	case string:
		*e = ConvoyDeliveryMode(s)
	default:
		return fmt.Errorf("unsupported scan type for ConvoyDeliveryMode: %T", src)
	}
	return nil
}

type NullConvoyDeliveryMode struct {
	ConvoyDeliveryMode ConvoyDeliveryMode
	Valid              bool // Valid is true if ConvoyDeliveryMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConvoyDeliveryMode) Scan(value interface{}) error {
	if value == nil {
		ns.ConvoyDeliveryMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConvoyDeliveryMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConvoyDeliveryMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConvoyDeliveryMode), nil
}
