// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ============================================================================
	// UTILITY Operations
	// ============================================================================
	// Count subscriptions for a specific endpoint (excluding a specific subscription)
	CountEndpointSubscriptions(ctx context.Context, arg CountEndpointSubscriptionsParams) (int64, error)
	// Unified count query for pagination prev row count
	CountPrevSubscriptions(ctx context.Context, arg CountPrevSubscriptionsParams) (int64, error)
	// Count all subscriptions across multiple projects
	CountProjectSubscriptions(ctx context.Context, projectIds []string) (int64, error)
	// Subscriptions Queries
	// ============================================================================
	// CREATE Operations
	// ============================================================================
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error
	// ============================================================================
	// DELETE Operations
	// ============================================================================
	DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (pgconn.CommandTag, error)
	DeleteSubscriptionEventTypes(ctx context.Context, subscriptionID string) error
	FetchCLISubscriptions(ctx context.Context, projectID string) ([]FetchCLISubscriptionsRow, error)
	// Fetch subscriptions that have been deleted
	FetchDeletedSubscriptions(ctx context.Context, arg FetchDeletedSubscriptionsParams) ([]FetchDeletedSubscriptionsRow, error)
	// Fetch new subscriptions created after last sync time
	FetchNewSubscriptions(ctx context.Context, arg FetchNewSubscriptionsParams) ([]FetchNewSubscriptionsRow, error)
	FetchSubscriptionByDeviceID(ctx context.Context, arg FetchSubscriptionByDeviceIDParams) (FetchSubscriptionByDeviceIDRow, error)
	// ============================================================================
	// FETCH Operations
	// ============================================================================
	FetchSubscriptionByID(ctx context.Context, arg FetchSubscriptionByIDParams) (FetchSubscriptionByIDRow, error)
	FetchSubscriptionsByEndpointID(ctx context.Context, arg FetchSubscriptionsByEndpointIDParams) ([]FetchSubscriptionsByEndpointIDRow, error)
	FetchSubscriptionsBySourceID(ctx context.Context, arg FetchSubscriptionsBySourceIDParams) ([]FetchSubscriptionsBySourceIDRow, error)
	// ============================================================================
	// BROADCAST & SYNC Operations
	// ============================================================================
	// Fetch subscriptions matching event type with pagination
	FetchSubscriptionsForBroadcast(ctx context.Context, arg FetchSubscriptionsForBroadcastParams) ([]FetchSubscriptionsForBroadcastRow, error)
	// ============================================================================
	// PAGINATED Operations
	// ============================================================================
	// @direction: 'next' for forward pagination, 'prev' for backward pagination
	// @has_endpoint_filter: true to filter by endpoint_ids, false to skip
	// @has_name_filter: true to filter by name, false to skip
	// Final select: reverse order for backward pagination to get DESC order
	FetchSubscriptionsPaginated(ctx context.Context, arg FetchSubscriptionsPaginatedParams) ([]FetchSubscriptionsPaginatedRow, error)
	// Fetch subscriptions that have been updated since last sync
	// Uses VALUES clause for input map (id, last_updated_at pairs)
	// @values_clause will be substituted with the actual VALUES
	FetchUpdatedSubscriptions(ctx context.Context, arg FetchUpdatedSubscriptionsParams) ([]FetchUpdatedSubscriptionsRow, error)
	InsertSubscriptionEventTypeFilters(ctx context.Context, subscriptionID pgtype.Text) error
	// Load all subscription configs for multiple projects with pagination
	LoadAllSubscriptionsConfiguration(ctx context.Context, arg LoadAllSubscriptionsConfigurationParams) ([]LoadAllSubscriptionsConfigurationRow, error)
	// ============================================================================
	// UPDATE Operations
	// ============================================================================
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (pgconn.CommandTag, error)
	UpsertSubscriptionEventTypes(ctx context.Context, arg UpsertSubscriptionEventTypesParams) error
}

var _ Querier = (*Queries)(nil)
