// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Count records before the given cursor (for pagination metadata)
	// Uses same filters as FetchMetaEventsPaginated
	//
	// This query counts how many records exist with ID > cursor
	// which tells us how many records are on previous pages
	CountPrevMetaEvents(ctx context.Context, arg CountPrevMetaEventsParams) (pgtype.Int8, error)
	// Meta Events Queries
	// Schema: convoy.meta_events
	// Columns: id, project_id, event_type, metadata, attempt, status, created_at, updated_at, deleted_at
	// ============================================================================
	// CREATE Operations
	// ============================================================================
	CreateMetaEvent(ctx context.Context, arg CreateMetaEventParams) error
	// ============================================================================
	// PAGINATED READ Operations
	// ============================================================================
	// Unified pagination query that handles:
	// - Bidirectional pagination (forward with 'next', backward with 'prev')
	// - Date range filtering
	// - Soft delete filtering (deleted_at IS NULL)
	//
	// Parameters:
	// @direction: 'next' for forward pagination, 'prev' for backward pagination
	// @cursor: ID of the last item from previous page (empty string for first page)
	// @project_id: Filter by project_id
	// @start_date: Start of date range filter
	// @end_date: End of date range filter
	// @limit_val: Number of records to fetch (should be PerPage + 1 for hasNext detection)
	// Final select: reverse order for backward pagination to maintain DESC ordering
	FetchMetaEventsPaginated(ctx context.Context, arg FetchMetaEventsPaginatedParams) ([]FetchMetaEventsPaginatedRow, error)
	// ============================================================================
	// READ Operations - Single Record
	// ============================================================================
	FindMetaEventByID(ctx context.Context, arg FindMetaEventByIDParams) (FindMetaEventByIDRow, error)
	// ============================================================================
	// UPDATE Operations
	// ============================================================================
	UpdateMetaEvent(ctx context.Context, arg UpdateMetaEventParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
