#!/usr/bin/env bash

#MISE description="Start Convoy server"
#MISE dir="{{ config_root }}"
#MISE depends=["build"]

set -e

echo "🚀 Starting backend server on: $CONVOY_HOST"

exec ./bin/convoy server
