// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDeliveriesByEndpointAndStatus = `-- name: CountDeliveriesByEndpointAndStatus :many
SELECT endpoint_id, status, COUNT(*) AS count
FROM convoy.event_deliveries
WHERE project_id = $1
  AND endpoint_id = ANY($2::TEXT[])
  AND status = ANY($3::TEXT[])
  AND created_at >= $4
  AND created_at <= $5
  AND deleted_at IS NULL
GROUP BY endpoint_id, status
`

type CountDeliveriesByEndpointAndStatusParams struct {
	ProjectID   pgtype.Text
	EndpointIds []string
	Statuses    []string
	StartDate   pgtype.Timestamptz
	EndDate     pgtype.Timestamptz
}

type CountDeliveriesByEndpointAndStatusRow struct {
	EndpointID pgtype.Text
	Status     string
	Count      pgtype.Int8
}

// CountDeliveriesByEndpointAndStatus returns per-endpoint counts for the given
// statuses over a date range. Used to compute the period (history) failure rate
// for the endpoints list and the per-endpoint reliability view. Restricted to the
// caller's status set so it stays index-friendly.
func (q *Queries) CountDeliveriesByEndpointAndStatus(ctx context.Context, arg CountDeliveriesByEndpointAndStatusParams) ([]CountDeliveriesByEndpointAndStatusRow, error) {
	rows, err := q.db.Query(ctx, countDeliveriesByEndpointAndStatus,
		arg.ProjectID,
		arg.EndpointIds,
		arg.Statuses,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDeliveriesByEndpointAndStatusRow
	for rows.Next() {
		var i CountDeliveriesByEndpointAndStatusRow
		if err := rows.Scan(&i.EndpointID, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDeliveriesByStatus = `-- name: CountDeliveriesByStatus :one

SELECT COUNT(id) AS count
FROM convoy.event_deliveries
WHERE status = $1
  AND (project_id = $2 OR $2 = '')
  AND created_at >= $3
  AND created_at <= $4
  AND deleted_at IS NULL
`

type CountDeliveriesByStatusParams struct {
	Status    pgtype.Text
	ProjectID pgtype.Text
	StartDate pgtype.Timestamptz
	EndDate   pgtype.Timestamptz
}

// ============================================================================
// Group 3: Count Operations
// ============================================================================
func (q *Queries) CountDeliveriesByStatus(ctx context.Context, arg CountDeliveriesByStatusParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, countDeliveriesByStatus,
		arg.Status,
		arg.ProjectID,
		arg.StartDate,
		arg.EndDate,
	)
	var count pgtype.Int8
	err := row.Scan(&count)
	return count, err
}

const countEventDeliveries = `-- name: CountEventDeliveries :one
SELECT COUNT(id) AS count
FROM convoy.event_deliveries
WHERE (project_id = $1 OR $1 = '')
  AND (event_id = $2 OR $2 = '')
  AND created_at >= $3
  AND created_at <= $4
  AND deleted_at IS NULL
  AND (CASE WHEN $5::BOOLEAN THEN endpoint_id = ANY($6::TEXT[]) ELSE true END)
  AND (CASE WHEN $7::BOOLEAN THEN status = ANY($8::TEXT[]) ELSE true END)
`

type CountEventDeliveriesParams struct {
	ProjectID      pgtype.Text
	EventID        pgtype.Text
	StartDate      pgtype.Timestamptz
	EndDate        pgtype.Timestamptz
	HasEndpointIds pgtype.Bool
	EndpointIds    []string
	HasStatus      pgtype.Bool
	Statuses       []string
}

func (q *Queries) CountEventDeliveries(ctx context.Context, arg CountEventDeliveriesParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, countEventDeliveries,
		arg.ProjectID,
		arg.EventID,
		arg.StartDate,
		arg.EndDate,
		arg.HasEndpointIds,
		arg.EndpointIds,
		arg.HasStatus,
		arg.Statuses,
	)
	var count pgtype.Int8
	err := row.Scan(&count)
	return count, err
}

const countExportedEventDeliveries = `-- name: CountExportedEventDeliveries :one
SELECT COUNT(*) AS count FROM convoy.event_deliveries
WHERE created_at < $1
  AND created_at >= $2
  AND deleted_at IS NULL
`

type CountExportedEventDeliveriesParams struct {
	CreatedAtEnd   pgtype.Timestamptz
	CreatedAtStart pgtype.Timestamptz
}

func (q *Queries) CountExportedEventDeliveries(ctx context.Context, arg CountExportedEventDeliveriesParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, countExportedEventDeliveries, arg.CreatedAtEnd, arg.CreatedAtStart)
	var count pgtype.Int8
	err := row.Scan(&count)
	return count, err
}

const exportEventDeliveries = `-- name: ExportEventDeliveries :many

SELECT ed.id,
       JSONB_BUILD_OBJECT(
           'uid', ed.id,
           'project_id', ed.project_id,
           'event_id', ed.event_id,
           'endpoint_id', ed.endpoint_id,
           'device_id', ed.device_id,
           'subscription_id', ed.subscription_id,
           'headers', ed.headers,
           'attempts', ed.attempts,
           'status', ed.status,
           'metadata', ed.metadata,
           'cli_metadata', ed.cli_metadata,
           'description', ed.description,
           'target_url', ed.target_url,
           'url_query_params', ed.url_query_params,
           'idempotency_key', ed.idempotency_key,
           'event_type', ed.event_type,
           'acknowledged_at', ed.acknowledged_at,
           'latency_seconds', ed.latency_seconds,
           'delivery_mode', ed.delivery_mode,
           'created_at', ed.created_at,
           'updated_at', ed.updated_at
       ) AS json_output
FROM convoy.event_deliveries AS ed
WHERE created_at < $1
  AND created_at >= $2
  AND (id > $3 OR $3 = '')
  AND deleted_at IS NULL
ORDER BY id
LIMIT $4
`

type ExportEventDeliveriesParams struct {
	CreatedAtEnd   pgtype.Timestamptz
	CreatedAtStart pgtype.Timestamptz
	Cursor         pgtype.Text
	PageLimit      pgtype.Int8
}

type ExportEventDeliveriesRow struct {
	ID         string
	JsonOutput []byte
}

// ============================================================================
// Group 7: Export Operations
// ============================================================================
func (q *Queries) ExportEventDeliveries(ctx context.Context, arg ExportEventDeliveriesParams) ([]ExportEventDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, exportEventDeliveries,
		arg.CreatedAtEnd,
		arg.CreatedAtStart,
		arg.Cursor,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportEventDeliveriesRow
	for rows.Next() {
		var i ExportEventDeliveriesRow
		if err := rows.Scan(&i.ID, &i.JsonOutput); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDiscardedEventDeliveries = `-- name: FindDiscardedEventDeliveries :many
SELECT
    id, project_id, event_id, subscription_id,
    headers, attempts, status, metadata, cli_metadata,
	COALESCE(target_url, '') AS target_url,
    COALESCE(idempotency_key, '') AS idempotency_key,
    COALESCE(url_query_params, '') AS url_query_params,
    description, created_at, updated_at,
    COALESCE(event_type, '') AS event_type,
    COALESCE(device_id, '') AS device_id,
    COALESCE(endpoint_id, '') AS endpoint_id,
    COALESCE(delivery_mode, 'at_least_once')::TEXT AS delivery_mode,
    acknowledged_at
FROM convoy.event_deliveries
WHERE status = 'Discarded'
  AND project_id = $1
  AND device_id = $2
  AND created_at >= $3
  AND created_at <= $4
  AND deleted_at IS NULL
`

type FindDiscardedEventDeliveriesParams struct {
	ProjectID pgtype.Text
	DeviceID  pgtype.Text
	StartDate pgtype.Timestamptz
	EndDate   pgtype.Timestamptz
}

type FindDiscardedEventDeliveriesRow struct {
	ID             string
	ProjectID      string
	EventID        string
	SubscriptionID string
	Headers        []byte
	Attempts       []byte
	Status         string
	Metadata       []byte
	CliMetadata    []byte
	TargetUrl      pgtype.Text
	IdempotencyKey pgtype.Text
	UrlQueryParams pgtype.Text
	Description    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	EventType      pgtype.Text
	DeviceID       pgtype.Text
	EndpointID     pgtype.Text
	DeliveryMode   pgtype.Text
	AcknowledgedAt pgtype.Timestamptz
}

func (q *Queries) FindDiscardedEventDeliveries(ctx context.Context, arg FindDiscardedEventDeliveriesParams) ([]FindDiscardedEventDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, findDiscardedEventDeliveries,
		arg.ProjectID,
		arg.DeviceID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindDiscardedEventDeliveriesRow
	for rows.Next() {
		var i FindDiscardedEventDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EventID,
			&i.SubscriptionID,
			&i.Headers,
			&i.Attempts,
			&i.Status,
			&i.Metadata,
			&i.CliMetadata,
			&i.TargetUrl,
			&i.IdempotencyKey,
			&i.UrlQueryParams,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventType,
			&i.DeviceID,
			&i.EndpointID,
			&i.DeliveryMode,
			&i.AcknowledgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEventDeliveriesByEventID = `-- name: FindEventDeliveriesByEventID :many
SELECT
    id, project_id, event_id, subscription_id,
    headers, attempts, status, metadata, cli_metadata,
	COALESCE(target_url, '') AS target_url,
    COALESCE(idempotency_key, '') AS idempotency_key,
    COALESCE(url_query_params, '') AS url_query_params,
    description, created_at, updated_at,
    COALESCE(event_type, '') AS event_type,
    COALESCE(device_id, '') AS device_id,
    COALESCE(endpoint_id, '') AS endpoint_id,
    COALESCE(delivery_mode, 'at_least_once')::TEXT AS delivery_mode,
    acknowledged_at
FROM convoy.event_deliveries
WHERE event_id = $1
  AND project_id = $2
  AND deleted_at IS NULL
`

type FindEventDeliveriesByEventIDParams struct {
	EventID   pgtype.Text
	ProjectID pgtype.Text
}

type FindEventDeliveriesByEventIDRow struct {
	ID             string
	ProjectID      string
	EventID        string
	SubscriptionID string
	Headers        []byte
	Attempts       []byte
	Status         string
	Metadata       []byte
	CliMetadata    []byte
	TargetUrl      pgtype.Text
	IdempotencyKey pgtype.Text
	UrlQueryParams pgtype.Text
	Description    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	EventType      pgtype.Text
	DeviceID       pgtype.Text
	EndpointID     pgtype.Text
	DeliveryMode   pgtype.Text
	AcknowledgedAt pgtype.Timestamptz
}

func (q *Queries) FindEventDeliveriesByEventID(ctx context.Context, arg FindEventDeliveriesByEventIDParams) ([]FindEventDeliveriesByEventIDRow, error) {
	rows, err := q.db.Query(ctx, findEventDeliveriesByEventID, arg.EventID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindEventDeliveriesByEventIDRow
	for rows.Next() {
		var i FindEventDeliveriesByEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EventID,
			&i.SubscriptionID,
			&i.Headers,
			&i.Attempts,
			&i.Status,
			&i.Metadata,
			&i.CliMetadata,
			&i.TargetUrl,
			&i.IdempotencyKey,
			&i.UrlQueryParams,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventType,
			&i.DeviceID,
			&i.EndpointID,
			&i.DeliveryMode,
			&i.AcknowledgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEventDeliveriesByIDs = `-- name: FindEventDeliveriesByIDs :many
SELECT
    id, project_id, event_id, subscription_id,
    headers, attempts, status, metadata, cli_metadata,
	COALESCE(target_url, '') AS target_url,
    COALESCE(idempotency_key, '') AS idempotency_key,
    COALESCE(url_query_params, '') AS url_query_params,
    description, created_at, updated_at,
    COALESCE(event_type, '') AS event_type,
    COALESCE(device_id, '') AS device_id,
    COALESCE(endpoint_id, '') AS endpoint_id,
    COALESCE(delivery_mode, 'at_least_once')::TEXT AS delivery_mode,
    acknowledged_at
FROM convoy.event_deliveries
WHERE id = ANY($1::TEXT[])
  AND project_id = $2
  AND deleted_at IS NULL
`

type FindEventDeliveriesByIDsParams struct {
	Ids       []string
	ProjectID pgtype.Text
}

type FindEventDeliveriesByIDsRow struct {
	ID             string
	ProjectID      string
	EventID        string
	SubscriptionID string
	Headers        []byte
	Attempts       []byte
	Status         string
	Metadata       []byte
	CliMetadata    []byte
	TargetUrl      pgtype.Text
	IdempotencyKey pgtype.Text
	UrlQueryParams pgtype.Text
	Description    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	EventType      pgtype.Text
	DeviceID       pgtype.Text
	EndpointID     pgtype.Text
	DeliveryMode   pgtype.Text
	AcknowledgedAt pgtype.Timestamptz
}

func (q *Queries) FindEventDeliveriesByIDs(ctx context.Context, arg FindEventDeliveriesByIDsParams) ([]FindEventDeliveriesByIDsRow, error) {
	rows, err := q.db.Query(ctx, findEventDeliveriesByIDs, arg.Ids, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindEventDeliveriesByIDsRow
	for rows.Next() {
		var i FindEventDeliveriesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EventID,
			&i.SubscriptionID,
			&i.Headers,
			&i.Attempts,
			&i.Status,
			&i.Metadata,
			&i.CliMetadata,
			&i.TargetUrl,
			&i.IdempotencyKey,
			&i.UrlQueryParams,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventType,
			&i.DeviceID,
			&i.EndpointID,
			&i.DeliveryMode,
			&i.AcknowledgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEventDeliveryByID = `-- name: FindEventDeliveryByID :one

SELECT
    ed.id, ed.project_id, ed.event_id, ed.subscription_id,
    ed.headers, ed.attempts, ed.status, ed.metadata, ed.cli_metadata,
	COALESCE(ed.target_url, '') AS target_url,
    COALESCE(ed.url_query_params, '') AS url_query_params,
    COALESCE(ed.idempotency_key, '') AS idempotency_key,
    ed.description, ed.created_at, ed.updated_at, ed.acknowledged_at,
    COALESCE(ed.event_type, '') AS event_type,
    COALESCE(ed.device_id, '') AS device_id,
    COALESCE(ed.endpoint_id, '') AS endpoint_id,
    COALESCE(ed.delivery_mode, 'at_least_once')::TEXT AS delivery_mode,
    COALESCE(ed.latency_seconds, 0) AS latency_seconds,
    COALESCE(ep.id, '') AS "endpoint_metadata.id",
    COALESCE(ep.name, '') AS "endpoint_metadata.name",
    COALESCE(ep.project_id, '') AS "endpoint_metadata.project_id",
    COALESCE(ep.support_email, '') AS "endpoint_metadata.support_email",
    COALESCE(ep.url, '') AS "endpoint_metadata.url",
    COALESCE(ep.owner_id, '') AS "endpoint_metadata.owner_id",
    COALESCE(ep.status, '') AS "endpoint_metadata.status",
    ep.deleted_at AS "endpoint_metadata.deleted_at",
    ev.id AS "event_metadata.id",
    ev.event_type AS "event_metadata.event_type",
    ev.created_at AS "event_metadata.created_at",
    COALESCE(d.id, '') AS "device_metadata.id",
    COALESCE(d.status, '') AS "device_metadata.status",
    COALESCE(d.host_name, '') AS "device_metadata.host_name",
    COALESCE(s.id, '') AS "source_metadata.id",
    COALESCE(s.name, '') AS "source_metadata.name"
FROM convoy.event_deliveries ed
LEFT JOIN convoy.endpoints ep ON ed.endpoint_id = ep.id
LEFT JOIN convoy.events ev ON ed.event_id = ev.id AND ev.project_id = ed.project_id
LEFT JOIN convoy.devices d ON ed.device_id = d.id
LEFT JOIN convoy.sources s ON s.id = ev.source_id
WHERE ed.deleted_at IS NULL
  AND ed.id = $1 AND ed.project_id = $2
`

type FindEventDeliveryByIDParams struct {
	ID        pgtype.Text
	ProjectID pgtype.Text
}

type FindEventDeliveryByIDRow struct {
	ID                           string
	ProjectID                    string
	EventID                      string
	SubscriptionID               string
	Headers                      []byte
	Attempts                     []byte
	Status                       string
	Metadata                     []byte
	CliMetadata                  []byte
	TargetUrl                    pgtype.Text
	UrlQueryParams               pgtype.Text
	IdempotencyKey               pgtype.Text
	Description                  string
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
	AcknowledgedAt               pgtype.Timestamptz
	EventType                    pgtype.Text
	DeviceID                     pgtype.Text
	EndpointID                   pgtype.Text
	DeliveryMode                 pgtype.Text
	LatencySeconds               pgtype.Numeric
	EndpointMetadataID           pgtype.Text
	EndpointMetadataName         pgtype.Text
	EndpointMetadataProjectID    pgtype.Text
	EndpointMetadataSupportEmail pgtype.Text
	EndpointMetadataUrl          pgtype.Text
	EndpointMetadataOwnerID      pgtype.Text
	EndpointMetadataStatus       pgtype.Text
	EndpointMetadataDeletedAt    pgtype.Timestamptz
	EventMetadataID              string
	EventMetadataEventType       string
	EventMetadataCreatedAt       pgtype.Timestamptz
	DeviceMetadataID             pgtype.Text
	DeviceMetadataStatus         pgtype.Text
	DeviceMetadataHostName       pgtype.Text
	SourceMetadataID             pgtype.Text
	SourceMetadataName           pgtype.Text
}

// ============================================================================
// Group 2: Find Operations
// ============================================================================
func (q *Queries) FindEventDeliveryByID(ctx context.Context, arg FindEventDeliveryByIDParams) (FindEventDeliveryByIDRow, error) {
	row := q.db.QueryRow(ctx, findEventDeliveryByID, arg.ID, arg.ProjectID)
	var i FindEventDeliveryByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EventID,
		&i.SubscriptionID,
		&i.Headers,
		&i.Attempts,
		&i.Status,
		&i.Metadata,
		&i.CliMetadata,
		&i.TargetUrl,
		&i.UrlQueryParams,
		&i.IdempotencyKey,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcknowledgedAt,
		&i.EventType,
		&i.DeviceID,
		&i.EndpointID,
		&i.DeliveryMode,
		&i.LatencySeconds,
		&i.EndpointMetadataID,
		&i.EndpointMetadataName,
		&i.EndpointMetadataProjectID,
		&i.EndpointMetadataSupportEmail,
		&i.EndpointMetadataUrl,
		&i.EndpointMetadataOwnerID,
		&i.EndpointMetadataStatus,
		&i.EndpointMetadataDeletedAt,
		&i.EventMetadataID,
		&i.EventMetadataEventType,
		&i.EventMetadataCreatedAt,
		&i.DeviceMetadataID,
		&i.DeviceMetadataStatus,
		&i.DeviceMetadataHostName,
		&i.SourceMetadataID,
		&i.SourceMetadataName,
	)
	return i, err
}

const findEventDeliveryByIDSlim = `-- name: FindEventDeliveryByIDSlim :one
SELECT
    id, project_id, event_id, subscription_id,
    headers, attempts, status, metadata, cli_metadata, description,
	COALESCE(target_url, '') AS target_url,
    COALESCE(url_query_params, '') AS url_query_params,
    COALESCE(idempotency_key, '') AS idempotency_key,
    created_at, updated_at,
    COALESCE(event_type, '') AS event_type,
    COALESCE(device_id, '') AS device_id,
    COALESCE(endpoint_id, '') AS endpoint_id,
    COALESCE(delivery_mode, 'at_least_once')::TEXT AS delivery_mode,
    acknowledged_at
FROM convoy.event_deliveries
WHERE deleted_at IS NULL
  AND project_id = $1 AND id = $2
`

type FindEventDeliveryByIDSlimParams struct {
	ProjectID pgtype.Text
	ID        pgtype.Text
}

type FindEventDeliveryByIDSlimRow struct {
	ID             string
	ProjectID      string
	EventID        string
	SubscriptionID string
	Headers        []byte
	Attempts       []byte
	Status         string
	Metadata       []byte
	CliMetadata    []byte
	Description    string
	TargetUrl      pgtype.Text
	UrlQueryParams pgtype.Text
	IdempotencyKey pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	EventType      pgtype.Text
	DeviceID       pgtype.Text
	EndpointID     pgtype.Text
	DeliveryMode   pgtype.Text
	AcknowledgedAt pgtype.Timestamptz
}

// Slim variant: does not JOIN endpoint/event/source/device tables. It still loads
// description so the worker's write-back via UpdateEventDeliveryMetadata stays
// faithful and does not clobber a stored description with an empty value.
func (q *Queries) FindEventDeliveryByIDSlim(ctx context.Context, arg FindEventDeliveryByIDSlimParams) (FindEventDeliveryByIDSlimRow, error) {
	row := q.db.QueryRow(ctx, findEventDeliveryByIDSlim, arg.ProjectID, arg.ID)
	var i FindEventDeliveryByIDSlimRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EventID,
		&i.SubscriptionID,
		&i.Headers,
		&i.Attempts,
		&i.Status,
		&i.Metadata,
		&i.CliMetadata,
		&i.Description,
		&i.TargetUrl,
		&i.UrlQueryParams,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventType,
		&i.DeviceID,
		&i.EndpointID,
		&i.DeliveryMode,
		&i.AcknowledgedAt,
	)
	return i, err
}

const findStuckEventDeliveriesByStatus = `-- name: FindStuckEventDeliveriesByStatus :many
SELECT id, project_id
FROM convoy.event_deliveries
WHERE status = $1
  AND created_at <= now() - make_interval(secs := 30)
  AND deleted_at IS NULL
FOR UPDATE SKIP LOCKED
LIMIT 1000
`

type FindStuckEventDeliveriesByStatusRow struct {
	ID        string
	ProjectID string
}

func (q *Queries) FindStuckEventDeliveriesByStatus(ctx context.Context, status pgtype.Text) ([]FindStuckEventDeliveriesByStatusRow, error) {
	rows, err := q.db.Query(ctx, findStuckEventDeliveriesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindStuckEventDeliveriesByStatusRow
	for rows.Next() {
		var i FindStuckEventDeliveriesByStatusRow
		if err := rows.Scan(&i.ID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hydrateEventDeliveriesPage = `-- name: HydrateEventDeliveriesPage :many

SELECT
    ed.id, ed.project_id, ed.event_id, ed.subscription_id,
    ed.headers, ed.attempts, ed.status, ed.metadata, ed.cli_metadata,
    COALESCE(ed.target_url, '') AS target_url,
    COALESCE(ed.url_query_params, '') AS url_query_params,
    COALESCE(ed.idempotency_key, '') AS idempotency_key,
    ed.description, ed.created_at, ed.updated_at, ed.acknowledged_at,
    COALESCE(ed.event_type, '') AS event_type,
    COALESCE(ed.device_id, '') AS device_id,
    COALESCE(ed.endpoint_id, '') AS endpoint_id,
    COALESCE(ed.delivery_mode, 'at_least_once')::TEXT AS delivery_mode,
    COALESCE(ed.latency_seconds, 0) AS latency_seconds,
    COALESCE(ep.id, '') AS "endpoint_metadata.id",
    COALESCE(ep.name, '') AS "endpoint_metadata.name",
    COALESCE(ep.project_id, '') AS "endpoint_metadata.project_id",
    COALESCE(ep.support_email, '') AS "endpoint_metadata.support_email",
    COALESCE(ep.url, '') AS "endpoint_metadata.url",
    COALESCE(ep.owner_id, '') AS "endpoint_metadata.owner_id",
    COALESCE(ep.status, '') AS "endpoint_metadata.status",
    ep.deleted_at AS "endpoint_metadata.deleted_at",
    ev.id AS "event_metadata.id",
    ev.event_type AS "event_metadata.event_type",
    ev.created_at AS "event_metadata.created_at",
    COALESCE(d.id, '') AS "device_metadata.id",
    COALESCE(d.status, '') AS "device_metadata.status",
    COALESCE(d.host_name, '') AS "device_metadata.host_name",
    COALESCE(s.id, '') AS "source_metadata.id",
    COALESCE(s.name, '') AS "source_metadata.name",
    COALESCE(s.idempotency_keys, '{}') AS "source_metadata.idempotency_keys"
FROM convoy.event_deliveries ed
LEFT JOIN convoy.endpoints ep ON ed.endpoint_id = ep.id
LEFT JOIN convoy.events ev ON ed.event_id = ev.id AND ev.project_id = ed.project_id
LEFT JOIN convoy.devices d ON ed.device_id = d.id
LEFT JOIN convoy.sources s ON s.id = ev.source_id
WHERE ed.project_id = $1
  AND ed.id = ANY($2::TEXT[])
  AND ed.deleted_at IS NULL
`

type HydrateEventDeliveriesPageParams struct {
	ProjectID pgtype.Text
	Ids       []string
}

type HydrateEventDeliveriesPageRow struct {
	ID                            string
	ProjectID                     string
	EventID                       string
	SubscriptionID                string
	Headers                       []byte
	Attempts                      []byte
	Status                        string
	Metadata                      []byte
	CliMetadata                   []byte
	TargetUrl                     pgtype.Text
	UrlQueryParams                pgtype.Text
	IdempotencyKey                pgtype.Text
	Description                   string
	CreatedAt                     pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
	AcknowledgedAt                pgtype.Timestamptz
	EventType                     pgtype.Text
	DeviceID                      pgtype.Text
	EndpointID                    pgtype.Text
	DeliveryMode                  pgtype.Text
	LatencySeconds                pgtype.Numeric
	EndpointMetadataID            pgtype.Text
	EndpointMetadataName          pgtype.Text
	EndpointMetadataProjectID     pgtype.Text
	EndpointMetadataSupportEmail  pgtype.Text
	EndpointMetadataUrl           pgtype.Text
	EndpointMetadataOwnerID       pgtype.Text
	EndpointMetadataStatus        pgtype.Text
	EndpointMetadataDeletedAt     pgtype.Timestamptz
	EventMetadataID               string
	EventMetadataEventType        string
	EventMetadataCreatedAt        pgtype.Timestamptz
	DeviceMetadataID              pgtype.Text
	DeviceMetadataStatus          pgtype.Text
	DeviceMetadataHostName        pgtype.Text
	SourceMetadataID              pgtype.Text
	SourceMetadataName            pgtype.Text
	SourceMetadataIdempotencyKeys []string
}

// ============================================================================
// Group 4: Pagination
// ============================================================================
// Hydrate a page of delivery ids. The id scan lives in Go (listFilter) so
// status, cursor, and other optional filters are real predicates, not CASE
// wrappers. Generic plans of the old InnerDesc/InnerAsc queries timed out on
// rare-status page 2 because those CASE clauses kept status and the keyset
// out of index cond. ORDER BY here is only the ~page of already-chosen ids.
func (q *Queries) HydrateEventDeliveriesPage(ctx context.Context, arg HydrateEventDeliveriesPageParams) ([]HydrateEventDeliveriesPageRow, error) {
	rows, err := q.db.Query(ctx, hydrateEventDeliveriesPage, arg.ProjectID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HydrateEventDeliveriesPageRow
	for rows.Next() {
		var i HydrateEventDeliveriesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EventID,
			&i.SubscriptionID,
			&i.Headers,
			&i.Attempts,
			&i.Status,
			&i.Metadata,
			&i.CliMetadata,
			&i.TargetUrl,
			&i.UrlQueryParams,
			&i.IdempotencyKey,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcknowledgedAt,
			&i.EventType,
			&i.DeviceID,
			&i.EndpointID,
			&i.DeliveryMode,
			&i.LatencySeconds,
			&i.EndpointMetadataID,
			&i.EndpointMetadataName,
			&i.EndpointMetadataProjectID,
			&i.EndpointMetadataSupportEmail,
			&i.EndpointMetadataUrl,
			&i.EndpointMetadataOwnerID,
			&i.EndpointMetadataStatus,
			&i.EndpointMetadataDeletedAt,
			&i.EventMetadataID,
			&i.EventMetadataEventType,
			&i.EventMetadataCreatedAt,
			&i.DeviceMetadataID,
			&i.DeviceMetadataStatus,
			&i.DeviceMetadataHostName,
			&i.SourceMetadataID,
			&i.SourceMetadataName,
			&i.SourceMetadataIdempotencyKeys,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadEventDeliveryIntervalsDaily = `-- name: LoadEventDeliveryIntervalsDaily :many

SELECT
    DATE_TRUNC('day', created_at) AS "data.group_only",
    TO_CHAR(DATE_TRUNC('day', created_at), 'yyyy-mm-dd') AS "data.total_time",
    EXTRACT('doy' FROM created_at) AS "data.index",
    COUNT(*) AS count
FROM convoy.event_deliveries
WHERE project_id = $1
  AND deleted_at IS NULL
  AND created_at >= $2
  AND created_at <= $3
  AND (CASE WHEN $4::BOOLEAN THEN endpoint_id = ANY($5::TEXT[]) ELSE true END)
GROUP BY "data.group_only", "data.index"
ORDER BY "data.group_only" ASC
`

type LoadEventDeliveryIntervalsDailyParams struct {
	ProjectID      pgtype.Text
	StartDate      pgtype.Timestamptz
	EndDate        pgtype.Timestamptz
	HasEndpointIds pgtype.Bool
	EndpointIds    []string
}

type LoadEventDeliveryIntervalsDailyRow struct {
	DataGroupOnly pgtype.Timestamptz
	DataTotalTime pgtype.Text
	DataIndex     pgtype.Numeric
	Count         pgtype.Int8
}

// ============================================================================
// Group 5: Intervals
// ============================================================================
func (q *Queries) LoadEventDeliveryIntervalsDaily(ctx context.Context, arg LoadEventDeliveryIntervalsDailyParams) ([]LoadEventDeliveryIntervalsDailyRow, error) {
	rows, err := q.db.Query(ctx, loadEventDeliveryIntervalsDaily,
		arg.ProjectID,
		arg.StartDate,
		arg.EndDate,
		arg.HasEndpointIds,
		arg.EndpointIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadEventDeliveryIntervalsDailyRow
	for rows.Next() {
		var i LoadEventDeliveryIntervalsDailyRow
		if err := rows.Scan(
			&i.DataGroupOnly,
			&i.DataTotalTime,
			&i.DataIndex,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadEventDeliveryIntervalsMonthly = `-- name: LoadEventDeliveryIntervalsMonthly :many
SELECT
    DATE_TRUNC('month', created_at) AS "data.group_only",
    TO_CHAR(DATE_TRUNC('month', created_at), 'yyyy-mm') AS "data.total_time",
    EXTRACT('month' FROM created_at) AS "data.index",
    COUNT(*) AS count
FROM convoy.event_deliveries
WHERE project_id = $1
  AND deleted_at IS NULL
  AND created_at >= $2
  AND created_at <= $3
  AND (CASE WHEN $4::BOOLEAN THEN endpoint_id = ANY($5::TEXT[]) ELSE true END)
GROUP BY "data.group_only", "data.index"
ORDER BY "data.group_only" ASC
`

type LoadEventDeliveryIntervalsMonthlyParams struct {
	ProjectID      pgtype.Text
	StartDate      pgtype.Timestamptz
	EndDate        pgtype.Timestamptz
	HasEndpointIds pgtype.Bool
	EndpointIds    []string
}

type LoadEventDeliveryIntervalsMonthlyRow struct {
	DataGroupOnly pgtype.Timestamptz
	DataTotalTime pgtype.Text
	DataIndex     pgtype.Numeric
	Count         pgtype.Int8
}

func (q *Queries) LoadEventDeliveryIntervalsMonthly(ctx context.Context, arg LoadEventDeliveryIntervalsMonthlyParams) ([]LoadEventDeliveryIntervalsMonthlyRow, error) {
	rows, err := q.db.Query(ctx, loadEventDeliveryIntervalsMonthly,
		arg.ProjectID,
		arg.StartDate,
		arg.EndDate,
		arg.HasEndpointIds,
		arg.EndpointIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadEventDeliveryIntervalsMonthlyRow
	for rows.Next() {
		var i LoadEventDeliveryIntervalsMonthlyRow
		if err := rows.Scan(
			&i.DataGroupOnly,
			&i.DataTotalTime,
			&i.DataIndex,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadEventDeliveryIntervalsWeekly = `-- name: LoadEventDeliveryIntervalsWeekly :many
SELECT
    DATE_TRUNC('week', created_at) AS "data.group_only",
    TO_CHAR(DATE_TRUNC('week', created_at), 'yyyy-mm-dd') AS "data.total_time",
    EXTRACT('week' FROM created_at) AS "data.index",
    COUNT(*) AS count
FROM convoy.event_deliveries
WHERE project_id = $1
  AND deleted_at IS NULL
  AND created_at >= $2
  AND created_at <= $3
  AND (CASE WHEN $4::BOOLEAN THEN endpoint_id = ANY($5::TEXT[]) ELSE true END)
GROUP BY "data.group_only", "data.index"
ORDER BY "data.group_only" ASC
`

type LoadEventDeliveryIntervalsWeeklyParams struct {
	ProjectID      pgtype.Text
	StartDate      pgtype.Timestamptz
	EndDate        pgtype.Timestamptz
	HasEndpointIds pgtype.Bool
	EndpointIds    []string
}

type LoadEventDeliveryIntervalsWeeklyRow struct {
	DataGroupOnly pgtype.Timestamptz
	DataTotalTime pgtype.Text
	DataIndex     pgtype.Numeric
	Count         pgtype.Int8
}

func (q *Queries) LoadEventDeliveryIntervalsWeekly(ctx context.Context, arg LoadEventDeliveryIntervalsWeeklyParams) ([]LoadEventDeliveryIntervalsWeeklyRow, error) {
	rows, err := q.db.Query(ctx, loadEventDeliveryIntervalsWeekly,
		arg.ProjectID,
		arg.StartDate,
		arg.EndDate,
		arg.HasEndpointIds,
		arg.EndpointIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadEventDeliveryIntervalsWeeklyRow
	for rows.Next() {
		var i LoadEventDeliveryIntervalsWeeklyRow
		if err := rows.Scan(
			&i.DataGroupOnly,
			&i.DataTotalTime,
			&i.DataIndex,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadEventDeliveryIntervalsYearly = `-- name: LoadEventDeliveryIntervalsYearly :many
SELECT
    DATE_TRUNC('year', created_at) AS "data.group_only",
    TO_CHAR(DATE_TRUNC('year', created_at), 'yyyy') AS "data.total_time",
    EXTRACT('year' FROM created_at) AS "data.index",
    COUNT(*) AS count
FROM convoy.event_deliveries
WHERE project_id = $1
  AND deleted_at IS NULL
  AND created_at >= $2
  AND created_at <= $3
  AND (CASE WHEN $4::BOOLEAN THEN endpoint_id = ANY($5::TEXT[]) ELSE true END)
GROUP BY "data.group_only", "data.index"
ORDER BY "data.group_only" ASC
`

type LoadEventDeliveryIntervalsYearlyParams struct {
	ProjectID      pgtype.Text
	StartDate      pgtype.Timestamptz
	EndDate        pgtype.Timestamptz
	HasEndpointIds pgtype.Bool
	EndpointIds    []string
}

type LoadEventDeliveryIntervalsYearlyRow struct {
	DataGroupOnly pgtype.Timestamptz
	DataTotalTime pgtype.Text
	DataIndex     pgtype.Numeric
	Count         pgtype.Int8
}

func (q *Queries) LoadEventDeliveryIntervalsYearly(ctx context.Context, arg LoadEventDeliveryIntervalsYearlyParams) ([]LoadEventDeliveryIntervalsYearlyRow, error) {
	rows, err := q.db.Query(ctx, loadEventDeliveryIntervalsYearly,
		arg.ProjectID,
		arg.StartDate,
		arg.EndDate,
		arg.HasEndpointIds,
		arg.EndpointIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadEventDeliveryIntervalsYearlyRow
	for rows.Next() {
		var i LoadEventDeliveryIntervalsYearlyRow
		if err := rows.Scan(
			&i.DataGroupOnly,
			&i.DataTotalTime,
			&i.DataIndex,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventDeliveryMetadata = `-- name: UpdateEventDeliveryMetadata :exec
WITH updated AS (
    UPDATE convoy.event_deliveries
    SET status = $1, metadata = $2, latency_seconds = $3, description = $4, updated_at = NOW()
    WHERE id = $5 AND project_id = $6 AND deleted_at IS NULL
    RETURNING created_at
)
INSERT INTO convoy.event_delivery_daily_counts_stale (day)
SELECT DISTINCT (created_at AT TIME ZONE 'UTC')::date
FROM updated
WHERE created_at < DATE_TRUNC('day', NOW() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
ON CONFLICT (day) DO NOTHING
`

type UpdateEventDeliveryMetadataParams struct {
	Status         pgtype.Text
	Metadata       []byte
	LatencySeconds pgtype.Numeric
	Description    pgtype.Text
	ID             pgtype.Text
	ProjectID      pgtype.Text
}

// Records the delivery's day as stale for the per-status rollup unless the row
// was created today, which the refresh window covers no matter when the next
// run lands. Yesterday does not qualify: a run a second after midnight covers
// today and yesterday as they are then, which no longer includes the day this
// update touched. Those markers cost an idempotent insert and are cleared by
// the window refresh itself, so they never reach the drain.
//
// Same statement as the status write, so a status change cannot land without
// the rollup learning that the day moved.
func (q *Queries) UpdateEventDeliveryMetadata(ctx context.Context, arg UpdateEventDeliveryMetadataParams) error {
	_, err := q.db.Exec(ctx, updateEventDeliveryMetadata,
		arg.Status,
		arg.Metadata,
		arg.LatencySeconds,
		arg.Description,
		arg.ID,
		arg.ProjectID,
	)
	return err
}

const updateStatusOfEventDeliveries = `-- name: UpdateStatusOfEventDeliveries :exec
WITH updated AS (
    UPDATE convoy.event_deliveries
    SET status = $1, description = $2, updated_at = NOW()
    WHERE (project_id = $3 OR $3 = '')
      AND id = ANY($4::TEXT[])
      AND deleted_at IS NULL
    RETURNING created_at
)
INSERT INTO convoy.event_delivery_daily_counts_stale (day)
SELECT DISTINCT (created_at AT TIME ZONE 'UTC')::date
FROM updated
WHERE created_at < DATE_TRUNC('day', NOW() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'
ON CONFLICT (day) DO NOTHING
`

type UpdateStatusOfEventDeliveriesParams struct {
	Status      pgtype.Text
	Description pgtype.Text
	ProjectID   pgtype.Text
	Ids         []string
}

// Marks stale days the same way as UpdateEventDeliveryMetadata. This is the
// path force resend and batch retry take, which is how a day long past the
// refresh window gets its statuses rewritten in bulk.
func (q *Queries) UpdateStatusOfEventDeliveries(ctx context.Context, arg UpdateStatusOfEventDeliveriesParams) error {
	_, err := q.db.Exec(ctx, updateStatusOfEventDeliveries,
		arg.Status,
		arg.Description,
		arg.ProjectID,
		arg.Ids,
	)
	return err
}
