// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDeliveriesByStatus = `-- name: CountDeliveriesByStatus :one

SELECT COUNT(id) AS count
FROM convoy.event_deliveries
WHERE status = $1
  AND (project_id = $2 OR $2 = '')
  AND created_at >= $3
  AND created_at <= $4
  AND deleted_at IS NULL
`

type CountDeliveriesByStatusParams struct {
	Status    pgtype.Text
	ProjectID pgtype.Text
	StartDate pgtype.Timestamptz
	EndDate   pgtype.Timestamptz
}

// ============================================================================
// Group 3: Count Operations
// ============================================================================
func (q *Queries) CountDeliveriesByStatus(ctx context.Context, arg CountDeliveriesByStatusParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, countDeliveriesByStatus,
		arg.Status,
		arg.ProjectID,
		arg.StartDate,
		arg.EndDate,
	)
	var count pgtype.Int8
	err := row.Scan(&count)
	return count, err
}

const countEventDeliveries = `-- name: CountEventDeliveries :one
SELECT COUNT(id) AS count
FROM convoy.event_deliveries
WHERE (project_id = $1 OR $1 = '')
  AND (event_id = $2 OR $2 = '')
  AND created_at >= $3
  AND created_at <= $4
  AND deleted_at IS NULL
  AND (CASE WHEN $5::BOOLEAN THEN endpoint_id = ANY($6::TEXT[]) ELSE true END)
  AND (CASE WHEN $7::BOOLEAN THEN status = ANY($8::TEXT[]) ELSE true END)
`

type CountEventDeliveriesParams struct {
	ProjectID      pgtype.Text
	EventID        pgtype.Text
	StartDate      pgtype.Timestamptz
	EndDate        pgtype.Timestamptz
	HasEndpointIds pgtype.Bool
	EndpointIds    []string
	HasStatus      pgtype.Bool
	Statuses       []string
}

func (q *Queries) CountEventDeliveries(ctx context.Context, arg CountEventDeliveriesParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, countEventDeliveries,
		arg.ProjectID,
		arg.EventID,
		arg.StartDate,
		arg.EndDate,
		arg.HasEndpointIds,
		arg.EndpointIds,
		arg.HasStatus,
		arg.Statuses,
	)
	var count pgtype.Int8
	err := row.Scan(&count)
	return count, err
}

const countExportedEventDeliveries = `-- name: CountExportedEventDeliveries :one
SELECT COUNT(*) AS count FROM convoy.event_deliveries
WHERE created_at < $1
  AND created_at >= $2
  AND deleted_at IS NULL
`

type CountExportedEventDeliveriesParams struct {
	CreatedAtEnd   pgtype.Timestamptz
	CreatedAtStart pgtype.Timestamptz
}

func (q *Queries) CountExportedEventDeliveries(ctx context.Context, arg CountExportedEventDeliveriesParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, countExportedEventDeliveries, arg.CreatedAtEnd, arg.CreatedAtStart)
	var count pgtype.Int8
	err := row.Scan(&count)
	return count, err
}

const countPrevEventDeliveries = `-- name: CountPrevEventDeliveries :one
SELECT COALESCE(COUNT(*), 0) AS count
FROM convoy.event_deliveries ed
WHERE ed.deleted_at IS NULL
  AND (ed.project_id = $1 OR $1 = '')
  AND (ed.event_id = $2 OR $2 = '')
  AND (ed.event_type = $3 OR $3 = '')
  AND ed.created_at >= $4
  AND ed.created_at <= $5
  AND (CASE WHEN $6::BOOLEAN THEN ed.endpoint_id = ANY($7::TEXT[]) ELSE true END)
  AND (CASE WHEN $8::BOOLEAN THEN ed.status = ANY($9::TEXT[]) ELSE true END)
  AND (CASE WHEN $10::BOOLEAN THEN ed.subscription_id = $11 ELSE true END)
  AND (CASE WHEN $12::BOOLEAN THEN ed.headers -> 'x-broker-message-id' ->> 0 = $13 ELSE true END)
  AND (CASE WHEN $14::BOOLEAN THEN ed.idempotency_key = $15 ELSE true END)
  AND (CASE
           WHEN $16::text = 'DESC' THEN ed.id > $17
           WHEN $16::text = 'ASC' THEN ed.id < $17
           ELSE ed.id > $17 END)
`

type CountPrevEventDeliveriesParams struct {
	ProjectID          pgtype.Text
	EventID            pgtype.Text
	EventType          pgtype.Text
	StartDate          pgtype.Timestamptz
	EndDate            pgtype.Timestamptz
	HasEndpointIds     pgtype.Bool
	EndpointIds        []string
	HasStatus          pgtype.Bool
	Statuses           []string
	HasSubscriptionID  pgtype.Bool
	SubscriptionID     pgtype.Text
	HasBrokerMessageID pgtype.Bool
	BrokerMessageID    pgtype.Text
	HasIdempotencyKey  pgtype.Bool
	IdempotencyKey     pgtype.Text
	SortOrder          pgtype.Text
	Cursor             pgtype.Text
}

func (q *Queries) CountPrevEventDeliveries(ctx context.Context, arg CountPrevEventDeliveriesParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, countPrevEventDeliveries,
		arg.ProjectID,
		arg.EventID,
		arg.EventType,
		arg.StartDate,
		arg.EndDate,
		arg.HasEndpointIds,
		arg.EndpointIds,
		arg.HasStatus,
		arg.Statuses,
		arg.HasSubscriptionID,
		arg.SubscriptionID,
		arg.HasBrokerMessageID,
		arg.BrokerMessageID,
		arg.HasIdempotencyKey,
		arg.IdempotencyKey,
		arg.SortOrder,
		arg.Cursor,
	)
	var count pgtype.Int8
	err := row.Scan(&count)
	return count, err
}

const exportEventDeliveries = `-- name: ExportEventDeliveries :many

SELECT ed.id,
       JSONB_BUILD_OBJECT(
           'uid', ed.id,
           'project_id', ed.project_id,
           'event_id', ed.event_id,
           'endpoint_id', ed.endpoint_id,
           'device_id', ed.device_id,
           'subscription_id', ed.subscription_id,
           'headers', ed.headers,
           'attempts', ed.attempts,
           'status', ed.status,
           'metadata', ed.metadata,
           'cli_metadata', ed.cli_metadata,
           'description', ed.description,
           'url_query_params', ed.url_query_params,
           'idempotency_key', ed.idempotency_key,
           'event_type', ed.event_type,
           'acknowledged_at', ed.acknowledged_at,
           'latency_seconds', ed.latency_seconds,
           'delivery_mode', ed.delivery_mode,
           'created_at', ed.created_at,
           'updated_at', ed.updated_at
       ) AS json_output
FROM convoy.event_deliveries AS ed
WHERE created_at < $1
  AND created_at >= $2
  AND (id > $3 OR $3 = '')
  AND deleted_at IS NULL
ORDER BY id
LIMIT $4
`

type ExportEventDeliveriesParams struct {
	CreatedAtEnd   pgtype.Timestamptz
	CreatedAtStart pgtype.Timestamptz
	Cursor         pgtype.Text
	PageLimit      pgtype.Int8
}

type ExportEventDeliveriesRow struct {
	ID         string
	JsonOutput []byte
}

// ============================================================================
// Group 7: Export Operations
// ============================================================================
func (q *Queries) ExportEventDeliveries(ctx context.Context, arg ExportEventDeliveriesParams) ([]ExportEventDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, exportEventDeliveries, arg.CreatedAtEnd, arg.CreatedAtStart, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportEventDeliveriesRow
	for rows.Next() {
		var i ExportEventDeliveriesRow
		if err := rows.Scan(&i.ID, &i.JsonOutput); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDiscardedEventDeliveries = `-- name: FindDiscardedEventDeliveries :many
SELECT
    id, project_id, event_id, subscription_id,
    headers, attempts, status, metadata, cli_metadata,
    COALESCE(idempotency_key, '') AS idempotency_key,
    COALESCE(url_query_params, '') AS url_query_params,
    description, created_at, updated_at,
    COALESCE(event_type, '') AS event_type,
    COALESCE(device_id, '') AS device_id,
    COALESCE(endpoint_id, '') AS endpoint_id,
    COALESCE(delivery_mode, 'at_least_once')::TEXT AS delivery_mode,
    acknowledged_at
FROM convoy.event_deliveries
WHERE status = 'Discarded'
  AND project_id = $1
  AND device_id = $2
  AND created_at >= $3
  AND created_at <= $4
  AND deleted_at IS NULL
`

type FindDiscardedEventDeliveriesParams struct {
	ProjectID pgtype.Text
	DeviceID  pgtype.Text
	StartDate pgtype.Timestamptz
	EndDate   pgtype.Timestamptz
}

type FindDiscardedEventDeliveriesRow struct {
	ID             string
	ProjectID      string
	EventID        string
	SubscriptionID string
	Headers        []byte
	Attempts       []byte
	Status         string
	Metadata       []byte
	CliMetadata    []byte
	IdempotencyKey pgtype.Text
	UrlQueryParams pgtype.Text
	Description    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	EventType      pgtype.Text
	DeviceID       pgtype.Text
	EndpointID     pgtype.Text
	DeliveryMode   pgtype.Text
	AcknowledgedAt pgtype.Timestamptz
}

func (q *Queries) FindDiscardedEventDeliveries(ctx context.Context, arg FindDiscardedEventDeliveriesParams) ([]FindDiscardedEventDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, findDiscardedEventDeliveries,
		arg.ProjectID,
		arg.DeviceID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindDiscardedEventDeliveriesRow
	for rows.Next() {
		var i FindDiscardedEventDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EventID,
			&i.SubscriptionID,
			&i.Headers,
			&i.Attempts,
			&i.Status,
			&i.Metadata,
			&i.CliMetadata,
			&i.IdempotencyKey,
			&i.UrlQueryParams,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventType,
			&i.DeviceID,
			&i.EndpointID,
			&i.DeliveryMode,
			&i.AcknowledgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEventDeliveriesByEventID = `-- name: FindEventDeliveriesByEventID :many
SELECT
    id, project_id, event_id, subscription_id,
    headers, attempts, status, metadata, cli_metadata,
    COALESCE(idempotency_key, '') AS idempotency_key,
    COALESCE(url_query_params, '') AS url_query_params,
    description, created_at, updated_at,
    COALESCE(event_type, '') AS event_type,
    COALESCE(device_id, '') AS device_id,
    COALESCE(endpoint_id, '') AS endpoint_id,
    COALESCE(delivery_mode, 'at_least_once')::TEXT AS delivery_mode,
    acknowledged_at
FROM convoy.event_deliveries
WHERE event_id = $1
  AND project_id = $2
  AND deleted_at IS NULL
`

type FindEventDeliveriesByEventIDParams struct {
	EventID   pgtype.Text
	ProjectID pgtype.Text
}

type FindEventDeliveriesByEventIDRow struct {
	ID             string
	ProjectID      string
	EventID        string
	SubscriptionID string
	Headers        []byte
	Attempts       []byte
	Status         string
	Metadata       []byte
	CliMetadata    []byte
	IdempotencyKey pgtype.Text
	UrlQueryParams pgtype.Text
	Description    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	EventType      pgtype.Text
	DeviceID       pgtype.Text
	EndpointID     pgtype.Text
	DeliveryMode   pgtype.Text
	AcknowledgedAt pgtype.Timestamptz
}

func (q *Queries) FindEventDeliveriesByEventID(ctx context.Context, arg FindEventDeliveriesByEventIDParams) ([]FindEventDeliveriesByEventIDRow, error) {
	rows, err := q.db.Query(ctx, findEventDeliveriesByEventID, arg.EventID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindEventDeliveriesByEventIDRow
	for rows.Next() {
		var i FindEventDeliveriesByEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EventID,
			&i.SubscriptionID,
			&i.Headers,
			&i.Attempts,
			&i.Status,
			&i.Metadata,
			&i.CliMetadata,
			&i.IdempotencyKey,
			&i.UrlQueryParams,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventType,
			&i.DeviceID,
			&i.EndpointID,
			&i.DeliveryMode,
			&i.AcknowledgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEventDeliveriesByIDs = `-- name: FindEventDeliveriesByIDs :many
SELECT
    id, project_id, event_id, subscription_id,
    headers, attempts, status, metadata, cli_metadata,
    COALESCE(idempotency_key, '') AS idempotency_key,
    COALESCE(url_query_params, '') AS url_query_params,
    description, created_at, updated_at,
    COALESCE(event_type, '') AS event_type,
    COALESCE(device_id, '') AS device_id,
    COALESCE(endpoint_id, '') AS endpoint_id,
    COALESCE(delivery_mode, 'at_least_once')::TEXT AS delivery_mode,
    acknowledged_at
FROM convoy.event_deliveries
WHERE id = ANY($1::TEXT[])
  AND project_id = $2
  AND deleted_at IS NULL
`

type FindEventDeliveriesByIDsParams struct {
	Ids       []string
	ProjectID pgtype.Text
}

type FindEventDeliveriesByIDsRow struct {
	ID             string
	ProjectID      string
	EventID        string
	SubscriptionID string
	Headers        []byte
	Attempts       []byte
	Status         string
	Metadata       []byte
	CliMetadata    []byte
	IdempotencyKey pgtype.Text
	UrlQueryParams pgtype.Text
	Description    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	EventType      pgtype.Text
	DeviceID       pgtype.Text
	EndpointID     pgtype.Text
	DeliveryMode   pgtype.Text
	AcknowledgedAt pgtype.Timestamptz
}

func (q *Queries) FindEventDeliveriesByIDs(ctx context.Context, arg FindEventDeliveriesByIDsParams) ([]FindEventDeliveriesByIDsRow, error) {
	rows, err := q.db.Query(ctx, findEventDeliveriesByIDs, arg.Ids, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindEventDeliveriesByIDsRow
	for rows.Next() {
		var i FindEventDeliveriesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EventID,
			&i.SubscriptionID,
			&i.Headers,
			&i.Attempts,
			&i.Status,
			&i.Metadata,
			&i.CliMetadata,
			&i.IdempotencyKey,
			&i.UrlQueryParams,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventType,
			&i.DeviceID,
			&i.EndpointID,
			&i.DeliveryMode,
			&i.AcknowledgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEventDeliveryByID = `-- name: FindEventDeliveryByID :one

SELECT
    ed.id, ed.project_id, ed.event_id, ed.subscription_id,
    ed.headers, ed.attempts, ed.status, ed.metadata, ed.cli_metadata,
    COALESCE(ed.url_query_params, '') AS url_query_params,
    COALESCE(ed.idempotency_key, '') AS idempotency_key,
    ed.description, ed.created_at, ed.updated_at, ed.acknowledged_at,
    COALESCE(ed.event_type, '') AS event_type,
    COALESCE(ed.device_id, '') AS device_id,
    COALESCE(ed.endpoint_id, '') AS endpoint_id,
    COALESCE(ed.delivery_mode, 'at_least_once')::TEXT AS delivery_mode,
    COALESCE(ed.latency_seconds, 0) AS latency_seconds,
    COALESCE(ep.id, '') AS "endpoint_metadata.id",
    COALESCE(ep.name, '') AS "endpoint_metadata.name",
    COALESCE(ep.project_id, '') AS "endpoint_metadata.project_id",
    COALESCE(ep.support_email, '') AS "endpoint_metadata.support_email",
    COALESCE(ep.url, '') AS "endpoint_metadata.url",
    COALESCE(ep.owner_id, '') AS "endpoint_metadata.owner_id",
    ev.id AS "event_metadata.id",
    ev.event_type AS "event_metadata.event_type",
    COALESCE(d.id, '') AS "device_metadata.id",
    COALESCE(d.status, '') AS "device_metadata.status",
    COALESCE(d.host_name, '') AS "device_metadata.host_name",
    COALESCE(s.id, '') AS "source_metadata.id",
    COALESCE(s.name, '') AS "source_metadata.name"
FROM convoy.event_deliveries ed
LEFT JOIN convoy.endpoints ep ON ed.endpoint_id = ep.id
LEFT JOIN convoy.events ev ON ed.event_id = ev.id
LEFT JOIN convoy.devices d ON ed.device_id = d.id
LEFT JOIN convoy.sources s ON s.id = ev.source_id
WHERE ed.deleted_at IS NULL
  AND ed.id = $1 AND ed.project_id = $2
`

type FindEventDeliveryByIDParams struct {
	ID        pgtype.Text
	ProjectID pgtype.Text
}

type FindEventDeliveryByIDRow struct {
	ID                           string
	ProjectID                    string
	EventID                      string
	SubscriptionID               string
	Headers                      []byte
	Attempts                     []byte
	Status                       string
	Metadata                     []byte
	CliMetadata                  []byte
	UrlQueryParams               pgtype.Text
	IdempotencyKey               pgtype.Text
	Description                  string
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
	AcknowledgedAt               pgtype.Timestamptz
	EventType                    pgtype.Text
	DeviceID                     pgtype.Text
	EndpointID                   pgtype.Text
	DeliveryMode                 pgtype.Text
	LatencySeconds               pgtype.Numeric
	EndpointMetadataID           pgtype.Text
	EndpointMetadataName         pgtype.Text
	EndpointMetadataProjectID    pgtype.Text
	EndpointMetadataSupportEmail pgtype.Text
	EndpointMetadataUrl          pgtype.Text
	EndpointMetadataOwnerID      pgtype.Text
	EventMetadataID              string
	EventMetadataEventType       string
	DeviceMetadataID             pgtype.Text
	DeviceMetadataStatus         pgtype.Text
	DeviceMetadataHostName       pgtype.Text
	SourceMetadataID             pgtype.Text
	SourceMetadataName           pgtype.Text
}

// ============================================================================
// Group 2: Find Operations
// ============================================================================
func (q *Queries) FindEventDeliveryByID(ctx context.Context, arg FindEventDeliveryByIDParams) (FindEventDeliveryByIDRow, error) {
	row := q.db.QueryRow(ctx, findEventDeliveryByID, arg.ID, arg.ProjectID)
	var i FindEventDeliveryByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EventID,
		&i.SubscriptionID,
		&i.Headers,
		&i.Attempts,
		&i.Status,
		&i.Metadata,
		&i.CliMetadata,
		&i.UrlQueryParams,
		&i.IdempotencyKey,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcknowledgedAt,
		&i.EventType,
		&i.DeviceID,
		&i.EndpointID,
		&i.DeliveryMode,
		&i.LatencySeconds,
		&i.EndpointMetadataID,
		&i.EndpointMetadataName,
		&i.EndpointMetadataProjectID,
		&i.EndpointMetadataSupportEmail,
		&i.EndpointMetadataUrl,
		&i.EndpointMetadataOwnerID,
		&i.EventMetadataID,
		&i.EventMetadataEventType,
		&i.DeviceMetadataID,
		&i.DeviceMetadataStatus,
		&i.DeviceMetadataHostName,
		&i.SourceMetadataID,
		&i.SourceMetadataName,
	)
	return i, err
}

const findEventDeliveryByIDSlim = `-- name: FindEventDeliveryByIDSlim :one
SELECT
    id, project_id, event_id, subscription_id,
    headers, attempts, status, metadata, cli_metadata,
    COALESCE(url_query_params, '') AS url_query_params,
    COALESCE(idempotency_key, '') AS idempotency_key,
    created_at, updated_at,
    COALESCE(event_type, '') AS event_type,
    COALESCE(device_id, '') AS device_id,
    COALESCE(endpoint_id, '') AS endpoint_id,
    COALESCE(delivery_mode, 'at_least_once')::TEXT AS delivery_mode,
    acknowledged_at
FROM convoy.event_deliveries
WHERE deleted_at IS NULL
  AND project_id = $1 AND id = $2
`

type FindEventDeliveryByIDSlimParams struct {
	ProjectID pgtype.Text
	ID        pgtype.Text
}

type FindEventDeliveryByIDSlimRow struct {
	ID             string
	ProjectID      string
	EventID        string
	SubscriptionID string
	Headers        []byte
	Attempts       []byte
	Status         string
	Metadata       []byte
	CliMetadata    []byte
	UrlQueryParams pgtype.Text
	IdempotencyKey pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	EventType      pgtype.Text
	DeviceID       pgtype.Text
	EndpointID     pgtype.Text
	DeliveryMode   pgtype.Text
	AcknowledgedAt pgtype.Timestamptz
}

// Slim variant: omits description and does not JOIN endpoint/event/source/device tables.
func (q *Queries) FindEventDeliveryByIDSlim(ctx context.Context, arg FindEventDeliveryByIDSlimParams) (FindEventDeliveryByIDSlimRow, error) {
	row := q.db.QueryRow(ctx, findEventDeliveryByIDSlim, arg.ProjectID, arg.ID)
	var i FindEventDeliveryByIDSlimRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EventID,
		&i.SubscriptionID,
		&i.Headers,
		&i.Attempts,
		&i.Status,
		&i.Metadata,
		&i.CliMetadata,
		&i.UrlQueryParams,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventType,
		&i.DeviceID,
		&i.EndpointID,
		&i.DeliveryMode,
		&i.AcknowledgedAt,
	)
	return i, err
}

const findStuckEventDeliveriesByStatus = `-- name: FindStuckEventDeliveriesByStatus :many
SELECT id, project_id
FROM convoy.event_deliveries
WHERE status = $1
  AND created_at <= now() - make_interval(secs := 30)
  AND deleted_at IS NULL
FOR UPDATE SKIP LOCKED
LIMIT 1000
`

type FindStuckEventDeliveriesByStatusRow struct {
	ID        string
	ProjectID string
}

func (q *Queries) FindStuckEventDeliveriesByStatus(ctx context.Context, status pgtype.Text) ([]FindStuckEventDeliveriesByStatusRow, error) {
	rows, err := q.db.Query(ctx, findStuckEventDeliveriesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindStuckEventDeliveriesByStatusRow
	for rows.Next() {
		var i FindStuckEventDeliveriesByStatusRow
		if err := rows.Scan(&i.ID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteProjectEventDeliveries = `-- name: HardDeleteProjectEventDeliveries :exec
DELETE FROM convoy.event_deliveries
WHERE project_id = $1
  AND created_at >= $2
  AND created_at <= $3
`

type HardDeleteProjectEventDeliveriesParams struct {
	ProjectID pgtype.Text
	StartDate pgtype.Timestamptz
	EndDate   pgtype.Timestamptz
}

func (q *Queries) HardDeleteProjectEventDeliveries(ctx context.Context, arg HardDeleteProjectEventDeliveriesParams) error {
	_, err := q.db.Exec(ctx, hardDeleteProjectEventDeliveries, arg.ProjectID, arg.StartDate, arg.EndDate)
	return err
}

const loadEventDeliveriesPaged = `-- name: LoadEventDeliveriesPaged :many

WITH filtered_deliveries AS (
    SELECT
        ed.id, ed.project_id, ed.event_id, ed.subscription_id,
        ed.headers, ed.attempts, ed.status, ed.metadata, ed.cli_metadata,
        COALESCE(ed.url_query_params, '') AS url_query_params,
        COALESCE(ed.idempotency_key, '') AS idempotency_key,
        ed.description, ed.created_at, ed.updated_at, ed.acknowledged_at,
        COALESCE(ed.event_type, '') AS event_type,
        COALESCE(ed.device_id, '') AS device_id,
        COALESCE(ed.endpoint_id, '') AS endpoint_id,
        COALESCE(ed.delivery_mode, 'at_least_once')::TEXT AS delivery_mode,
        COALESCE(ed.latency_seconds, 0) AS latency_seconds,
        COALESCE(ep.id, '') AS "endpoint_metadata.id",
        COALESCE(ep.name, '') AS "endpoint_metadata.name",
        COALESCE(ep.project_id, '') AS "endpoint_metadata.project_id",
        COALESCE(ep.support_email, '') AS "endpoint_metadata.support_email",
        COALESCE(ep.url, '') AS "endpoint_metadata.url",
        COALESCE(ep.owner_id, '') AS "endpoint_metadata.owner_id",
        ev.id AS "event_metadata.id",
        ev.event_type AS "event_metadata.event_type",
        COALESCE(d.id, '') AS "device_metadata.id",
        COALESCE(d.status, '') AS "device_metadata.status",
        COALESCE(d.host_name, '') AS "device_metadata.host_name",
        COALESCE(s.id, '') AS "source_metadata.id",
        COALESCE(s.name, '') AS "source_metadata.name",
        COALESCE(s.idempotency_keys, '{}') AS "source_metadata.idempotency_keys"
    FROM convoy.event_deliveries ed
    LEFT JOIN convoy.endpoints ep ON ed.endpoint_id = ep.id
    LEFT JOIN convoy.events ev ON ed.event_id = ev.id
    LEFT JOIN convoy.devices d ON ed.device_id = d.id
    LEFT JOIN convoy.sources s ON s.id = ev.source_id
    WHERE ed.deleted_at IS NULL
      AND (ed.project_id = $2 OR $2 = '')
      AND (ed.event_id = $3 OR $3 = '')
      AND (ed.event_type = $4 OR $4 = '')
      AND ed.created_at >= $5
      AND ed.created_at <= $6
      -- Endpoint filter
      AND (CASE WHEN $7::BOOLEAN THEN ed.endpoint_id = ANY($8::TEXT[]) ELSE true END)
      -- Status filter
      AND (CASE WHEN $9::BOOLEAN THEN ed.status = ANY($10::TEXT[]) ELSE true END)
      -- Subscription filter
      AND (CASE WHEN $11::BOOLEAN THEN ed.subscription_id = $12 ELSE true END)
      -- Broker message ID filter
      -- TODO(perf): consider GIN index on metadata->>'broker_message_id' (cross-cutting concern across 9+ files)
      AND (CASE WHEN $13::BOOLEAN THEN ed.headers -> 'x-broker-message-id' ->> 0 = $14 ELSE true END)
      -- Idempotency key filter
      AND (CASE WHEN $15::BOOLEAN THEN ed.idempotency_key = $16 ELSE true END)
      -- Cursor pagination
      AND (
        CASE
            WHEN $17 = '' THEN true
            WHEN ($1::text = 'DESC' AND $18::text = 'next') OR ($1::text = 'ASC' AND $18::text = 'prev') THEN ed.id <= $17
            WHEN ($1::text = 'ASC' AND $18::text = 'next') OR ($1::text = 'DESC' AND $18::text = 'prev') THEN ed.id >= $17
            ELSE true
        END
      )
    ORDER BY
        CASE WHEN ($1::text = 'DESC' AND $18::text = 'next') OR ($1::text = 'ASC' AND $18::text = 'prev') THEN ed.id END DESC,
        CASE WHEN ($1::text = 'ASC' AND $18::text = 'next') OR ($1::text = 'DESC' AND $18::text = 'prev') THEN ed.id END ASC
    LIMIT $19
)
SELECT id, project_id, event_id, subscription_id,
       headers, attempts, status, metadata, cli_metadata,
       url_query_params, idempotency_key, description,
       created_at, updated_at, acknowledged_at,
       event_type, device_id, endpoint_id, delivery_mode, latency_seconds,
       "endpoint_metadata.id", "endpoint_metadata.name", "endpoint_metadata.project_id",
       "endpoint_metadata.support_email", "endpoint_metadata.url", "endpoint_metadata.owner_id",
       "event_metadata.id", "event_metadata.event_type",
       "device_metadata.id", "device_metadata.status", "device_metadata.host_name",
       "source_metadata.id", "source_metadata.name", "source_metadata.idempotency_keys"
FROM filtered_deliveries
ORDER BY
    CASE WHEN $1::text = 'DESC' THEN id END DESC,
    CASE WHEN $1::text = 'ASC' THEN id END ASC
`

type LoadEventDeliveriesPagedParams struct {
	SortOrder          pgtype.Text
	ProjectID          pgtype.Text
	EventID            pgtype.Text
	EventType          pgtype.Text
	StartDate          pgtype.Timestamptz
	EndDate            pgtype.Timestamptz
	HasEndpointIds     pgtype.Bool
	EndpointIds        []string
	HasStatus          pgtype.Bool
	Statuses           []string
	HasSubscriptionID  pgtype.Bool
	SubscriptionID     pgtype.Text
	HasBrokerMessageID pgtype.Bool
	BrokerMessageID    pgtype.Text
	HasIdempotencyKey  pgtype.Bool
	IdempotencyKey     pgtype.Text
	Cursor             pgtype.Text
	Direction          pgtype.Text
	PageLimit          pgtype.Int8
}

type LoadEventDeliveriesPagedRow struct {
	ID                            string
	ProjectID                     string
	EventID                       string
	SubscriptionID                string
	Headers                       []byte
	Attempts                      []byte
	Status                        string
	Metadata                      []byte
	CliMetadata                   []byte
	UrlQueryParams                pgtype.Text
	IdempotencyKey                pgtype.Text
	Description                   string
	CreatedAt                     pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
	AcknowledgedAt                pgtype.Timestamptz
	EventType                     pgtype.Text
	DeviceID                      pgtype.Text
	EndpointID                    pgtype.Text
	DeliveryMode                  pgtype.Text
	LatencySeconds                pgtype.Numeric
	EndpointMetadataID            pgtype.Text
	EndpointMetadataName          pgtype.Text
	EndpointMetadataProjectID     pgtype.Text
	EndpointMetadataSupportEmail  pgtype.Text
	EndpointMetadataUrl           pgtype.Text
	EndpointMetadataOwnerID       pgtype.Text
	EventMetadataID               string
	EventMetadataEventType        string
	DeviceMetadataID              pgtype.Text
	DeviceMetadataStatus          pgtype.Text
	DeviceMetadataHostName        pgtype.Text
	SourceMetadataID              pgtype.Text
	SourceMetadataName            pgtype.Text
	SourceMetadataIdempotencyKeys []string
}

// ============================================================================
// Group 4: Pagination
// ============================================================================
// TODO(perf): this query fetches all columns including large JSONB blobs (metadata, headers, cli_metadata).
// Consider a "slim" paginated query variant that omits heavy columns for list views.
func (q *Queries) LoadEventDeliveriesPaged(ctx context.Context, arg LoadEventDeliveriesPagedParams) ([]LoadEventDeliveriesPagedRow, error) {
	rows, err := q.db.Query(ctx, loadEventDeliveriesPaged,
		arg.SortOrder,
		arg.ProjectID,
		arg.EventID,
		arg.EventType,
		arg.StartDate,
		arg.EndDate,
		arg.HasEndpointIds,
		arg.EndpointIds,
		arg.HasStatus,
		arg.Statuses,
		arg.HasSubscriptionID,
		arg.SubscriptionID,
		arg.HasBrokerMessageID,
		arg.BrokerMessageID,
		arg.HasIdempotencyKey,
		arg.IdempotencyKey,
		arg.Cursor,
		arg.Direction,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadEventDeliveriesPagedRow
	for rows.Next() {
		var i LoadEventDeliveriesPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EventID,
			&i.SubscriptionID,
			&i.Headers,
			&i.Attempts,
			&i.Status,
			&i.Metadata,
			&i.CliMetadata,
			&i.UrlQueryParams,
			&i.IdempotencyKey,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcknowledgedAt,
			&i.EventType,
			&i.DeviceID,
			&i.EndpointID,
			&i.DeliveryMode,
			&i.LatencySeconds,
			&i.EndpointMetadataID,
			&i.EndpointMetadataName,
			&i.EndpointMetadataProjectID,
			&i.EndpointMetadataSupportEmail,
			&i.EndpointMetadataUrl,
			&i.EndpointMetadataOwnerID,
			&i.EventMetadataID,
			&i.EventMetadataEventType,
			&i.DeviceMetadataID,
			&i.DeviceMetadataStatus,
			&i.DeviceMetadataHostName,
			&i.SourceMetadataID,
			&i.SourceMetadataName,
			&i.SourceMetadataIdempotencyKeys,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadEventDeliveryIntervalsDaily = `-- name: LoadEventDeliveryIntervalsDaily :many

SELECT
    DATE_TRUNC('day', created_at) AS "data.group_only",
    TO_CHAR(DATE_TRUNC('day', created_at), 'yyyy-mm-dd') AS "data.total_time",
    EXTRACT('doy' FROM created_at) AS "data.index",
    COUNT(*) AS count
FROM convoy.event_deliveries
WHERE project_id = $1
  AND deleted_at IS NULL
  AND created_at >= $2
  AND created_at <= $3
  AND (CASE WHEN $4::BOOLEAN THEN endpoint_id = ANY($5::TEXT[]) ELSE true END)
GROUP BY "data.group_only", "data.index"
ORDER BY "data.group_only" ASC
`

type LoadEventDeliveryIntervalsDailyParams struct {
	ProjectID      pgtype.Text
	StartDate      pgtype.Timestamptz
	EndDate        pgtype.Timestamptz
	HasEndpointIds pgtype.Bool
	EndpointIds    []string
}

type LoadEventDeliveryIntervalsDailyRow struct {
	DataGroupOnly pgtype.Timestamptz
	DataTotalTime pgtype.Text
	DataIndex     pgtype.Numeric
	Count         pgtype.Int8
}

// ============================================================================
// Group 5: Intervals
// ============================================================================
func (q *Queries) LoadEventDeliveryIntervalsDaily(ctx context.Context, arg LoadEventDeliveryIntervalsDailyParams) ([]LoadEventDeliveryIntervalsDailyRow, error) {
	rows, err := q.db.Query(ctx, loadEventDeliveryIntervalsDaily,
		arg.ProjectID,
		arg.StartDate,
		arg.EndDate,
		arg.HasEndpointIds,
		arg.EndpointIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadEventDeliveryIntervalsDailyRow
	for rows.Next() {
		var i LoadEventDeliveryIntervalsDailyRow
		if err := rows.Scan(
			&i.DataGroupOnly,
			&i.DataTotalTime,
			&i.DataIndex,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadEventDeliveryIntervalsMonthly = `-- name: LoadEventDeliveryIntervalsMonthly :many
SELECT
    DATE_TRUNC('month', created_at) AS "data.group_only",
    TO_CHAR(DATE_TRUNC('month', created_at), 'yyyy-mm') AS "data.total_time",
    EXTRACT('month' FROM created_at) AS "data.index",
    COUNT(*) AS count
FROM convoy.event_deliveries
WHERE project_id = $1
  AND deleted_at IS NULL
  AND created_at >= $2
  AND created_at <= $3
  AND (CASE WHEN $4::BOOLEAN THEN endpoint_id = ANY($5::TEXT[]) ELSE true END)
GROUP BY "data.group_only", "data.index"
ORDER BY "data.group_only" ASC
`

type LoadEventDeliveryIntervalsMonthlyParams struct {
	ProjectID      pgtype.Text
	StartDate      pgtype.Timestamptz
	EndDate        pgtype.Timestamptz
	HasEndpointIds pgtype.Bool
	EndpointIds    []string
}

type LoadEventDeliveryIntervalsMonthlyRow struct {
	DataGroupOnly pgtype.Timestamptz
	DataTotalTime pgtype.Text
	DataIndex     pgtype.Numeric
	Count         pgtype.Int8
}

func (q *Queries) LoadEventDeliveryIntervalsMonthly(ctx context.Context, arg LoadEventDeliveryIntervalsMonthlyParams) ([]LoadEventDeliveryIntervalsMonthlyRow, error) {
	rows, err := q.db.Query(ctx, loadEventDeliveryIntervalsMonthly,
		arg.ProjectID,
		arg.StartDate,
		arg.EndDate,
		arg.HasEndpointIds,
		arg.EndpointIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadEventDeliveryIntervalsMonthlyRow
	for rows.Next() {
		var i LoadEventDeliveryIntervalsMonthlyRow
		if err := rows.Scan(
			&i.DataGroupOnly,
			&i.DataTotalTime,
			&i.DataIndex,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadEventDeliveryIntervalsWeekly = `-- name: LoadEventDeliveryIntervalsWeekly :many
SELECT
    DATE_TRUNC('week', created_at) AS "data.group_only",
    TO_CHAR(DATE_TRUNC('week', created_at), 'yyyy-mm-dd') AS "data.total_time",
    EXTRACT('week' FROM created_at) AS "data.index",
    COUNT(*) AS count
FROM convoy.event_deliveries
WHERE project_id = $1
  AND deleted_at IS NULL
  AND created_at >= $2
  AND created_at <= $3
  AND (CASE WHEN $4::BOOLEAN THEN endpoint_id = ANY($5::TEXT[]) ELSE true END)
GROUP BY "data.group_only", "data.index"
ORDER BY "data.group_only" ASC
`

type LoadEventDeliveryIntervalsWeeklyParams struct {
	ProjectID      pgtype.Text
	StartDate      pgtype.Timestamptz
	EndDate        pgtype.Timestamptz
	HasEndpointIds pgtype.Bool
	EndpointIds    []string
}

type LoadEventDeliveryIntervalsWeeklyRow struct {
	DataGroupOnly pgtype.Timestamptz
	DataTotalTime pgtype.Text
	DataIndex     pgtype.Numeric
	Count         pgtype.Int8
}

func (q *Queries) LoadEventDeliveryIntervalsWeekly(ctx context.Context, arg LoadEventDeliveryIntervalsWeeklyParams) ([]LoadEventDeliveryIntervalsWeeklyRow, error) {
	rows, err := q.db.Query(ctx, loadEventDeliveryIntervalsWeekly,
		arg.ProjectID,
		arg.StartDate,
		arg.EndDate,
		arg.HasEndpointIds,
		arg.EndpointIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadEventDeliveryIntervalsWeeklyRow
	for rows.Next() {
		var i LoadEventDeliveryIntervalsWeeklyRow
		if err := rows.Scan(
			&i.DataGroupOnly,
			&i.DataTotalTime,
			&i.DataIndex,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadEventDeliveryIntervalsYearly = `-- name: LoadEventDeliveryIntervalsYearly :many
SELECT
    DATE_TRUNC('year', created_at) AS "data.group_only",
    TO_CHAR(DATE_TRUNC('year', created_at), 'yyyy') AS "data.total_time",
    EXTRACT('year' FROM created_at) AS "data.index",
    COUNT(*) AS count
FROM convoy.event_deliveries
WHERE project_id = $1
  AND deleted_at IS NULL
  AND created_at >= $2
  AND created_at <= $3
  AND (CASE WHEN $4::BOOLEAN THEN endpoint_id = ANY($5::TEXT[]) ELSE true END)
GROUP BY "data.group_only", "data.index"
ORDER BY "data.group_only" ASC
`

type LoadEventDeliveryIntervalsYearlyParams struct {
	ProjectID      pgtype.Text
	StartDate      pgtype.Timestamptz
	EndDate        pgtype.Timestamptz
	HasEndpointIds pgtype.Bool
	EndpointIds    []string
}

type LoadEventDeliveryIntervalsYearlyRow struct {
	DataGroupOnly pgtype.Timestamptz
	DataTotalTime pgtype.Text
	DataIndex     pgtype.Numeric
	Count         pgtype.Int8
}

func (q *Queries) LoadEventDeliveryIntervalsYearly(ctx context.Context, arg LoadEventDeliveryIntervalsYearlyParams) ([]LoadEventDeliveryIntervalsYearlyRow, error) {
	rows, err := q.db.Query(ctx, loadEventDeliveryIntervalsYearly,
		arg.ProjectID,
		arg.StartDate,
		arg.EndDate,
		arg.HasEndpointIds,
		arg.EndpointIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadEventDeliveryIntervalsYearlyRow
	for rows.Next() {
		var i LoadEventDeliveryIntervalsYearlyRow
		if err := rows.Scan(
			&i.DataGroupOnly,
			&i.DataTotalTime,
			&i.DataIndex,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProjectEventDeliveries = `-- name: SoftDeleteProjectEventDeliveries :exec

UPDATE convoy.event_deliveries
SET deleted_at = NOW()
WHERE project_id = $1
  AND created_at >= $2
  AND created_at <= $3
  AND deleted_at IS NULL
`

type SoftDeleteProjectEventDeliveriesParams struct {
	ProjectID pgtype.Text
	StartDate pgtype.Timestamptz
	EndDate   pgtype.Timestamptz
}

// ============================================================================
// Group 6: Delete Operations
// ============================================================================
func (q *Queries) SoftDeleteProjectEventDeliveries(ctx context.Context, arg SoftDeleteProjectEventDeliveriesParams) error {
	_, err := q.db.Exec(ctx, softDeleteProjectEventDeliveries, arg.ProjectID, arg.StartDate, arg.EndDate)
	return err
}

const updateEventDeliveryMetadata = `-- name: UpdateEventDeliveryMetadata :exec
UPDATE convoy.event_deliveries
SET status = $1, metadata = $2, latency_seconds = $3, updated_at = NOW()
WHERE id = $4 AND project_id = $5 AND deleted_at IS NULL
`

type UpdateEventDeliveryMetadataParams struct {
	Status         pgtype.Text
	Metadata       []byte
	LatencySeconds pgtype.Numeric
	ID             pgtype.Text
	ProjectID      pgtype.Text
}

func (q *Queries) UpdateEventDeliveryMetadata(ctx context.Context, arg UpdateEventDeliveryMetadataParams) error {
	_, err := q.db.Exec(ctx, updateEventDeliveryMetadata,
		arg.Status,
		arg.Metadata,
		arg.LatencySeconds,
		arg.ID,
		arg.ProjectID,
	)
	return err
}

const updateStatusOfEventDeliveries = `-- name: UpdateStatusOfEventDeliveries :exec
UPDATE convoy.event_deliveries
SET status = $1, description = $2, updated_at = NOW()
WHERE (project_id = $3 OR $3 = '')
  AND id = ANY($4::TEXT[])
  AND deleted_at IS NULL
`

type UpdateStatusOfEventDeliveriesParams struct {
	Status      pgtype.Text
	Description pgtype.Text
	ProjectID   pgtype.Text
	Ids         []string
}

func (q *Queries) UpdateStatusOfEventDeliveries(ctx context.Context, arg UpdateStatusOfEventDeliveriesParams) error {
	_, err := q.db.Exec(ctx, updateStatusOfEventDeliveries,
		arg.Status,
		arg.Description,
		arg.ProjectID,
		arg.Ids,
	)
	return err
}
