name: Validate PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: read
  statuses: write

jobs:
  semantic-pr-title:
    name: Conventional PR title
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            perf
            refactor
            docs
            test
            chore
            ci
            build
          scopes: |
            controlplane
            dataplane
            dashboard
            infra
            release
            docs
            deps
            build
          requireScope: true
          subjectPattern: ^.+$
          subjectPatternError: Subject must not be empty
