name: Build and run immune tests
on:
  push:
    branches:
      - daniel/feat/add_immune_to_ci

jobs:
  test:
    if: ${{ !(contains(github.head_ref, 'ui/')) || !(contains(github.head_ref, 'cms/')) }}
    strategy:
      matrix:
        go-version: [ 1.16.x, 1.17.x ]
        immune-test-file-names: [ "immune-push-events.json" ]
        immune-version: [ "v0.1.2" ]
        mongodb-version: [ "4.0", "4.2", "4.4" ]
        redis-version: [ "6.2.6" ]

    runs-on: ubuntu-latest
    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.4.1
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Start Redis v${{ matrix.redis-version }}
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}
          redis-port: 6379

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Pull immune
        run: go get github.com/frain-dev/immune@${{ matrix.immune-version }}

      - name: Setup custom host for endpoint
        run: echo "127.0.0.1 www.endpoint.url" | sudo tee -a /etc/hosts

      - name: Pull certgen
        uses: danvixent/certgen-action@v0.1.2
        with:
          os: ${{ runner.os }}
          certgen-version: 0.1.2

      - name: Build immune
        run: |
          cd $(go env GOPATH)/pkg/mod/github.com/frain-dev/immune@${{ matrix.immune-version }} && \
          go build -o $(go env GOPATH)/bin/immune ./cmd/*

      - name: Start convoy
        run: |
          go run ./cmd server &
        env:
          PORT: 5005
          CONVOY_RETRY_LIMIT: "3"
          CONVOY_INTERVAL_SECONDS: "10"
          CONVOY_SIGNATURE_HEADER: "X-Convoy-CI"
          CONVOY_STRATEGY_TYPE: "default"
          CONVOY_SIGNATURE_HASH: "SHA256"
          CONVOY_DB_TYPE: "mongodb"
          CONVOY_SENTRY_DSN: "https://0264d31341b0465c8a9d05d6202f1298@o1164445.ingest.sentry.io/6253559"
          CONVOY_DB_DSN: "mongodb://localhost:27017/testdb"
          CONVOY_REDIS_DSN: "redis://localhost:6379"
          CONVOY_QUEUE_PROVIDER: "redis"

      - name: Sleep to allow convoy server start
        run: sleep 50

      - name: Run immune tests
        env:
          IMMUNE_EVENT_TARGET_URL: https://endpoint.url:9098
          IMMUNE_SSL: true
          IMMUNE_SSL_KEY_FILE: echo $LOCALHOST_KEY_FILE #has been set by certgen
          IMMUNE_SSL_CERT_FILE: echo $LOCALHOST_CRT_FILE #has been set by certgen
        run: |
          cd ./immune-test-files && \
          immune run --config ./${{ matrix.immune-test-file-names }}
