name: Build and run all tests
on:
  push:
    branches:
      - daniel/feat/add_immune_to_ci

jobs:
  test:
    if: ${{ !(contains(github.head_ref, 'ui/')) || !(contains(github.head_ref, 'cms/')) }}
    strategy:
      matrix:
        go-version: [ 1.16.x, 1.17.x ]
        endpoint-url: [ "www.endpoint.url" ]
        immune-test-file-names: [ "immune-push-events.json" ]
        os: [ ubuntu-latest, macos-latest ]
        immune-version: [ "v0.1.2" ]
        mongodb-version: [ "4.0", "4.2", "4.4" ]
        redis-version: [ "6.2.6" ]

    runs-on: ubuntu-latest
    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.4.1
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Pull immune
        run: go get github.com/frain-dev/immune@${{ matrix.immune-version }}

      - name: Setup custom host for endpoint
        run: echo "127.0.0.1 ${{ matrix.endpoint-url }}" | sudo tee -a /etc/hosts

      - name: Build immune
        run: |
          cd $(go env GOPATH)/pkg/mod/github.com/frain-dev/immune@${{ matrix.immune-version }} && \
          go build -o $(go env GOPATH)/bin/immune ./cmd/*

      - name: Check out code
        uses: actions/checkout@v2

      - name: Start convoy
        run: |
          go run ./cmd server &
        env:
          CONVOY_DB_DSN: "mongodb://localhost:27017/testdb"
          CONVOY_REDIS_DSN: "redis://localhost:6379"

      - name: Sleep to allow convoy server start
        run: sleep 3

      - name: Run immune tests
        run: |
          cd ./immune-test-files && \
          export IMMUNE_EVENT_TARGET_URL=${{ matrix.endpoint-url }} && \
          immune run --config ./${{ matrix.immune-test-file-names }}
