name: golangci-lint
on:
    pull_request:

jobs:
    golangci:
        if: ${{ !(contains(github.head_ref, 'ui/')) || !(contains(github.head_ref, 'cms/')) }}
        name: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
            - name: golangci-lint
              uses: golangci/golangci-lint-action@9fae48acfc02a90574d7c304a1758ef9895495fa
              with:
                  version: v2.12.2
                  only-new-issues: true
                  args: --timeout 3m --verbose
